### ISSUE TITLE
Setup CI/CD

### ISSUE THREAD

**Issue by deniszh** [graphite-project/docker-graphite-statsd#10]
To build latest release and upload to Docker Hub.

**Comment by evolv34** [comment]
Hi Deniszh, we can setup CI/CD using docker hub. I can setup. Can I get access to `https://hub.docker.com/r/graphiteapp/graphite-statsd/` on docker ? this is my account name `chanhub`.

**Comment by deniszh** [comment]
Thank you, but it is more reminder for me then call for help. I’ll do it
soon.

**Comment by deniszh** [comment]
I did it on https://hub.docker.com/r/graphiteapp/docker-graphite-statsd/
It looks like it's not possible to enable it on https://hub.docker.com/r/graphiteapp/graphite-statsd/ :(
Not sure how to proceed further. Probably I should abandon old repo...

**Comment by bebehei** [comment]
You should go on and delete the old repo and recreate the repo `graphiteapp/graphite-statsd` as an automated build. Dockerhub will crawl the stuff automatically.

IIUC, you're pushing the automatically built images manually to the unautomated repo? If I remember it right, deleting the `graphiteapp/graphite-statsd` repo and setting it up again, will lead dockerhub build all tags then automatically.

Also another comment on the CI/CD pipeline: It would be great, if you remove the codacy part. Any change to the dockerfile will immediately lead to a "failed" pipeline. This makes no sense.

**Comment by deniszh** [comment]
Well, most of codacy issues are valid - https://github.com/graphite-project/docker-graphite-statsd/commit/95eb6e7830d640d3ea1ff32d9830fbb1bff76873
