### ISSUE TITLE
Overriding LOG_LISTENER_CONN_SUCCESS & ENABLE_TAGS through env

### ISSUE THREAD

**Issue by alexsegura** [graphite-project/docker-graphite-statsd#101]
Hello,

As indicated in graphite-project/carbon#34, the logs are making too much noise. 
Is there a way to set `LOG_LISTENER_CONN_SUCCESS` & `ENABLE_TAGS` through env vars, which would be way more easier that mounting & editing `carbon.conf` file?

Or alternatively, a way to completely turn off logging for Carbon? 
Maybe I'm missing something, but I didn't find a way.

Thank you 🙂

**Comment by deniszh** [comment]
Currently, carbon.conf does not contain any ability for customization, because it's a real config and not a Python code (comparing with `local_settings.py`).
It can be probably extended with some templating, overridable by env variables, though - but it's need to be implemented.

**Comment by alexsegura** [comment]
Ok. Is there a way to disable logging then? I see it uses `twisted.python.log` but found no way to disable it.
