### ISSUE TITLE
Cannot start the container in SCC enforced k8s environment

### ISSUE THREAD

**Issue by praveenbvarrier** [graphite-project/docker-graphite-statsd#104]
Pod fails to start in kubernetes cluster when Security context is sa.scc.uid-range is enforced. 

This context will not allow the entrypoint to start as root neither will have access to write into /var or /etc.

All the startup scripts for this docker image are highly dependent on root access.

**Comment by deniszh** [comment]
Yes, it's probably possible to make it run under non root user, but it will require some efforts.

**Comment by haljin** [comment]
Is there any plans for this? This is a pretty serious issue - nobody should be running images as root in K8s.

**Comment by deniszh** [comment]
@haljin : I doubt that is possible to address that in current image. I think it should be addressed to run carbon, relay, graphite-web and redis is separate images, and no nginx.

**Comment by paulcgt** [comment]
@deniszh : Why would you need to run them in separate containers? I realise that Nginx on port 80 could be a problem, but that can be run on a port > 1024. Is there another reason I'm unaware of?

**Comment by deniszh** [comment]
runit runs only as root and it's a core component which runs multiply processes in same container. So, without it you just need go use separate containers with Nginx (if needed), Relay (if needed), (multiply) Carbon caches (if needed), graphite-web and redis (if needed).
This project is just made for simplification of setup above.

**Comment by deniszh** [comment]
I mean, running separate process in separate container is quite vital part of K8S ideology anyway, and current setup (using runit for running multiple processes on same container) is bit against of whole idea. So, for K8S it's needs to be remade IMO.

**Comment by paulcgt** [comment]
As opposed to the OP, my target is Swarm, not k8s, and in my set up I can run the container as root - I'm just trying not to do so. In time I expect it'll be mandatory to run it as non-root so this may be something I'll work on refactoring in future. And sure, I take your point about separating out all the processes into different containers.

**Comment by deniszh** [comment]
That's a my whole point - no need to refactor, just new project needed, indeed.
