### ISSUE TITLE
Image in Dockerhub needs freshening

### ISSUE THREAD

**Issue by qhartman** [graphite-project/docker-graphite-statsd#105]
The image at dockerhub doesn't seem to have the PR that I submitted last month in it, so anyone who has a large installation will have a long startup delay as the init script scans whisper directories for pid files, which it should never find there. If there's a better way to request an image refresh, I'm happy to do that.

**Comment by deniszh** [comment]
Oh, I forgot to update it. I have autobuild repo btw - https://hub.docker.com/r/graphiteapp/docker-graphite-statsd, which builds fro master branch.
Will make a release.

**Comment by deniszh** [comment]
1.1.5-12 released and pushed
