### ISSUE TITLE
Allow volumes to be optional

### ISSUE THREAD

**Issue by te-online** [graphite-project/docker-graphite-statsd#108]
I'd like to use graphite on a cloud stack that provides me with a limited number of volumes. This docker image requires 8 volumes to be mounted, which is a lot. I don't mind losing logs and other data when restarting the container, but there's no way for me to override this, not even in an inherited Dockerfile (as far as I can see).

Grafana, to name an example, moved away from this approach and allows specifying exactly which volumes I'd like to mount. See https://grafana.com/docs/installation/docker/#removal-of-implicit-volumes

The only change required would be removing the `VOLUME` statements from the Dockerfile.

**Comment by deniszh** [comment]
Hi @te-online,
Maybe I'm not a getting use case here.
1. Why many volumes is bad?
2. If I remove volume how then we can have separate logs or configs? 

For now looks like you need to just remove `VOLUME` statements from Dockerfile, build own image and use it.

**Comment by te-online** [comment]
Hi @deniszh, thanks for asking these important questions:

Re 1.: Many volumes are bad in my case, because there's a hard limit my docker hosting provider set configuring how many volumes I can use.

Re 2.: I'm not asking to remove support for volumes, I'm asking to remove the implicit creation of volumes within your Dockerfile.

There are a couple of downsides using the `VOLUME` statement and not really any upsides, are there? Although not an ultimate resource, I still think this article sums it up nicely https://boxboat.com/2017/01/23/volumes-and-dockerfiles-dont-mix/

> looks like you need to just remove VOLUME statements from Dockerfile, build own image and use it

Yes, this is exactly how I did it for now. But this means, updating the image went from being a one-click operation (restarting the container using the `latest` tag) to a multi-step-process. (I need to update my own image, push it to my own registry, and then I can restart the container.)

Of course I'd prefer the easier solution 😊 
But I can also understand if there are any reasons to keep the `VOLUME` statement.

**Comment by deniszh** [comment]
Hi @te-online ,

Sorry for my ignorance, I just can't understand how I can remove `VOLUME` stanza from Dockerfile and will have compatibility for users who already using volumes. If it's possible - I would like to do so. If not - then unfortunately, I would prefer to keep compatibility.

**Comment by te-online** [comment]
Hi @deniszh – Thanks for following up 😊 It's alright, I don't have a definite answer right now, I had to read up on this test it. My guess is that it wouldn't make a difference to existing users, but I can't be sure. Maybe there'll be someone else with a solution or I'll check it out at some point. For now, let's close this.
