### ISSUE TITLE
Can't run container via Docker-compose 

### ISSUE THREAD

**Issue by qlikviewsense** [graphite-project/docker-graphite-statsd#109]
Hi, glad to post here 

I've had no luck trying to run the container via docker-compose.

It runs but ports seems closed, maybe an NGINX issue

This is my yaml portion of code 

`graphite:
    image : graphiteapp/graphite-statsd
    user: "0"
    ports:
      - "8280:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - /var/data/app/graphite:/opt/graphite/storage
      - /var/data/config/graphite:/opt/graphite/webapp/graphite/functions/custom
      - /var/data/config/nginx:/etc/nginx
      - /var/data/config/statsd:/opt/statsd/config
      - /var/data/log/graphite:/var/log
`
if i start docker container with `docker run -d\
 --name graphite\
 --restart=always\
 -p 80:80\
 -p 2003-2004:2003-2004\
 -p 2023-2024:2023-2024\
 -p 8125:8125/udp\
 -p 8126:8126\
 graphiteapp/graphite-statsd
`
it runs fine ( e.g i can access {host}:8280 and get Graphite Django web app

What am i missing? Thanks to anyone who'll spend his time for my ( maybe ) dumb question

**Comment by deniszh** [comment]
Hi @qlikviewsense ,
First, your yaml lost formatting. Second - it's not really clear why it's not working, i.e. what exactly happening in that case. 
You can try bundled compose file - https://github.com/graphite-project/docker-graphite-statsd/blob/master/docker-compose.yml

**Comment by qlikviewsense** [comment]
Hi Deniszh, thank you for your reply. 

I looked at docker-compose.yml but it doesn't reference any container, i thought it was a typo, just `build:context` i never used, my fault, sorry, so i tried to build yaml by myself. Here's why.

As i tried to explain, if i start the container via 

`docker run -d --name graphite --restart=always -p 8280:80 -p 2003-2004:2003-2004 -p 2023-2024:2023-2024 -p 8125:8125/udp -p 8126:8126 graphiteapp/graphite-statsd`
 
i get a valid statsd endpoint where i can send metrics ( e.g. via the example `while true; do echo -n "example:$((RANDOM % 100))|c" | nc -w 1 -u 127.0.0.1 8125; done` ) and get access to localhost:8280 for Graphite Web 

As a rule, if i convert a `docker run xxxx` in a valid docker-compose.yaml file , i get the same behavior from the same container. 

In this case i failed i.e. i can't get the sample code to work and can't get access to localhost:8280 for Graphite Web.

Hope it's clear, sorry for my poor desciption
My best regards

**Comment by qlikviewsense** [comment]
Sorry for late reply.
As for my tentative, i tried to also mount docker volumes , according to repo info `mounted volumes`
I had nginx locked due to the lack of  a local copy of `/etc/nginx/*.*` files  : you can't map a pre-defined docker volume without its expected contents.
Thanks for your kind reply
