### ISSUE TITLE
docker run fails when mounting empty volume to /opt/statsd

### ISSUE THREAD

**Issue by melkamar** [graphite-project/docker-graphite-statsd#11]
Currently the init script `conf/etc/my_init.d/01_conf_init.sh` performs this action:
```
if [[ -z $statsd_dir_contents ]]; then
  git clone -b v0.7.2 https://github.com/etsy/statsd.git /opt/statsd
  cp $conf_dir/opt/statsd/config.js /opt/statsd/config.js
fi
```

However, there is no such file in `$conf_dir/opt/statsd/`, there are two - `config_tcp.js` and `config_udp.js`. 

I guess the solution would be to only copy one of them (I don't know `statsd` well enough, but I assume it requires exactly one config file). 

Workaround is not mounting the volume there, but this is a bug.

**Comment by deniszh** [comment]
Default is udp, let me fix that.

**Comment by deniszh** [comment]
Should be fixed now
