### ISSUE TITLE
Inserted metrics, no graphs

### ISSUE THREAD

**Issue by macksam0** [graphite-project/docker-graphite-statsd#112]
Hi everybody.

I was sending metrics to 2003 and 2004 ports. 2003 with bash using the 'echo' command and 2004 with Python-Pickle. Both methods create the metrics names and I can see into the Metrics Folder, but when I try to get the graphic, nothing happens.
But, if I send the metric to 8125 port using the 'echo bash' command, the metrics is created and the graph is rendered. 
The problem is that I need to use Carbon Plaintext or Pickle to send the timestamp (is a requirement).

Is necessary set something else to get the graphics for the sent metrics?

Thanks for your help, and sorry about my English.

![image](https://user-images.githubusercontent.com/9540131/63741279-abb23580-c851-11e9-8e30-29bc504c1ecf.png)

**Comment by deniszh** [comment]
Hi @macksam0 ,

Probably you need to provide more details, how do you sending metrics to plaintext and pickle protocol. Which OS do you use btw?
