### ISSUE TITLE
How to change URL of Graphite Web?

### ISSUE THREAD

**Issue by dmint007** [graphite-project/docker-graphite-statsd#113]
I've been trying to change carbon's URL from `localhost` to `<dynamic>:8125`. I've been editing my os.environ `GRAPHITE_ALLOWED_HOSTS` with no avail.

**Comment by deniszh** [comment]
Hi @dmint007 ,
Which URL?  Could you please elaborate what you trying to achieve? 
Port 8125 is already occupied by `statsd` btw.

**Comment by dmint007** [comment]
> Hi @dmint007 ,
> Which URL? Could you please elaborate what you trying to achieve?
> Port 8125 is already occupied by `statsd` btw.

I'm trying to change `Graphite-web` url from `http://localhost` to anything else, like `http://localhost:8100` as I cannot use `localhost` because it's already taken by another of my services.

**Comment by dmint007** [comment]
Found the solution.

In the `docker-compose.yml` file, change the port `80:80` > `8100:80`.
