### ISSUE TITLE
nginx version security issue -- can it be upgraded to 1.16.1

### ISSUE THREAD

**Issue by Torawk** [graphite-project/docker-graphite-statsd#114]
Hello,

  I'm using graphite along with Icinga and although not externally accessible, noticed this nginx vulnerability:

https://www.nginx.com/blog/nginx-updates-mitigate-august-2019-http-2-vulnerabilities/

Checked the lastest from dockerhub for graphite-project/docker-graphite-statsd and noticed:

```
/ # nginx -v
nginx version: nginx/1.16.0
```

I did a bit of digging and alpine will install 1.16.1, which addresses the issue.  So can we get a new build and image on dockerhub with this latest version?

**Comment by deniszh** [comment]
Not sure if relevant. But it's good to have anyway.

**Comment by deniszh** [comment]
Fixed in [1.1.5-13](https://github.com/graphite-project/docker-graphite-statsd/releases/tag/v1.1.5-13)

**Comment by Torawk** [comment]
Thanks for the very fast response and resolution!
