### ISSUE TITLE
Disable TagDb

### ISSUE THREAD

**Issue by throrin19** [graphite-project/docker-graphite-statsd#115]
Hi,

I just want to know if it's possible to disable TagDb in this project ?

I see the var GRAPHITE_TAGDB is setted in local sqLite server but it's possible to make the value to None to disable the tagDB ?

Thanks in advance

**Comment by deniszh** [comment]
Hi @throrin19 ,

You mean by default? You can disable it in your installation by `GRAPHITE_TAGDB` environment variable. I thing `-e GRAPHITE_TAGDB=None` should do the trick.

**Comment by nikolas** [comment]
When I start up the container with `docker run -e GRAPHITE_TAGDB=None`, graphite-web returns a 500 error.
