### ISSUE TITLE
GRAPHITE_WSGI_REQUEST_TIMEOUT has no effect

### ISSUE THREAD

**Issue by hamelg** [graphite-project/docker-graphite-statsd#119]
The documentation says about this tunable :
maximum number of seconds that a request is allowed to run before the daemon process is restarted

But if you test a slow request which takes more than the timeout, the worker processes it completely and never restarts.
This issue gives some explanations :
https://github.com/benoitc/gunicorn/issues/2086

The workaround is to set GRAPHITE_WSGI_THREADS=1

**Comment by deniszh** [comment]
OK, I will set GRAPHITE_WSGI_THREADS=1 by default in new release.

**Comment by deniszh** [comment]
Fixed in 1.1.6-1
