### ISSUE TITLE
Building doesn't result in working image

### ISSUE THREAD

**Issue by jebotz** [graphite-project/docker-graphite-statsd#122]
Cloning this repo and then doing "docker build -t graphiteapp/graphite-statsd ." does not currently result in a working image.  Running it gives this error:

  File "/opt/graphite/lib/python3.7/site-packages/gunicorn/sock.py", line 14, in <module>
    from gunicorn.socketfromfd import fromfd
  File "/opt/graphite/lib/python3.7/site-packages/gunicorn/socketfromfd.py", line 26, in <module>
    raise OSError('libc not found')
OSError: libc not found

Apparently gunicorn 20.0.0 has a new dependency on libc; so the two possible solutions are to add
libc to the alpine build or to make sure gunicorn is at verison 19.9.0 when it's installed by pip.  I've tested both, and either resolves the problem.

This does raise the interesting point that to ensure repeatable builds, all python packages installed with pip should probably have their versions specified.

**Comment by deniszh** [comment]
Well. To ensure repeatable builds _evertything_ should their versions specified, every linux package, not only python. I'm not ready for implementing this, so, let's start with pinning `gunicorn`

**Comment by deniszh** [comment]
Fixed in master.

**Comment by deniszh** [comment]
Thanks for reporting!

**Comment by jebotz** [comment]
> Well. To ensure repeatable builds _evertything_ should their versions specified, every linux package, not only python. I'm not ready for implementing this, so, let's start with pinning `gunicorn`

Well not exactly... everything provided by a distribution (i.e. alpine packages) should already have their dependencies in order and you *are* "pinning" the alpine version.  And for all the stuff that comes from git repos you specify default versions, so they don't change by themselves either.  But pip is a crap-shoot... any package that gets upgraded in the PyPI can break the build, and over time that's increasingly likely to happen, so they really *should* all be pinned to last "verified working" version.  I suspect the same goes for node packages?  I'm not very familiar with npm.
