### ISSUE TITLE
[Q] What is the difference between both official docker hub repos?

### ISSUE THREAD

**Issue by christian-weiss** [graphite-project/docker-graphite-statsd#125]
In user/organisation profile "graphiteapp" at docker hub:
https://hub.docker.com/u/graphiteapp
are two docker hub repos listed:
https://hub.docker.com/r/graphiteapp/graphite-statsd
https://hub.docker.com/r/graphiteapp/docker-graphite-statsd

What is the difference? ("Overview" page/tab looks identical)

On https://hub.docker.com/r/graphiteapp/graphite-statsd a link to its github repo and the "Dockerfile" page/tab is missing. Please add it.
I guess both are pointing to the same github repo. 
I guess https://hub.docker.com/r/graphiteapp/graphite-statsd is used as a stable release channel and https://hub.docker.com/r/graphiteapp/docker-graphite-statsd as a development release channel. Would be cool if you leave a statement on the "Overview" page/tab about it (with links to each other).

**Comment by deniszh** [comment]
https://github.com/graphite-project/docker-graphite-statsd/issues/117#issuecomment-541126381

Just included clarification in README. Unfortunately, both Docker Hub repos producing from the same Github repo, thus it's not possible to alter "Overwiew" tab separately, it's automatically synced with README.
<img width="262" alt="Screenshot 2020-02-23 at 12 13 40" src="https://user-images.githubusercontent.com/1227222/75111056-fa406100-5635-11ea-9eda-e08cc7bcae1c.png">

**Comment by christian-weiss** [comment]
Thanks for the README.md update.

You can enable the "Link to Github" and "Dockerfile" page/tab by:
1) login to docker hub (WebUI)
2) go to https://hub.docker.com/r/graphiteapp/graphite-statsd
3) click on "Manage Repository"
4) "Builds" / "Link to Github", then select your Github Username / Organisation + Repo Name
5) disable "Autobuild" and click save

This way you still have manual builds for your docker hub repo, but now it is linked to the Github repo and "Dockerfile" page/tab will become visable.

**Comment by christian-weiss** [comment]
BTW: You could make https://hub.docker.com/r/graphiteapp/graphite-statsd to ignore changes on your master branch and only do autobuild when you tag a github commit with a git tag (one tag for each official stable release). That way you can control when to release something as stable without being forced to do manual builds / releases.

**Comment by christian-weiss** [comment]
Hint: Push only one git tag at a time, as docker hub do not support "webhook events" with more then one new git tag.

**Comment by deniszh** [comment]
https://hub.docker.com/r/graphiteapp/graphite-statsd  have no autobuild enabled.
Only https://hub.docker.com/r/graphiteapp/docker-graphite-statsd  have autobuild. I always do manual builds there.
So, https://hub.docker.com/r/graphiteapp/docker-graphite-statsd  syncing to github.
IIRC it's not possible to have autobuild enabled on existing repo, so, that's a reason why https://hub.docker.com/r/graphiteapp/docker-graphite-statsd was created.

**Comment by deniszh** [comment]
Also, autobuilds not building arm/arm64 platforms, only amd64. And also there's no possibility to manually add arm/arm64 builds to existing tag with amd64 build.

**Comment by christian-weiss** [comment]
There is no restriction on docker hub repos. You can configure the "link to github" at any time incl. on existing docker hub repos. You can have multiple docker hub repos linked to a single github repo. And you can enable and disable "autobuild" for each docker hub repo independently from the other docker hub repos. Please do the "link to github" procedure above for https://hub.docker.com/r/graphiteapp/graphite-statsd, even if you plan to do manual build and releases, instead of autobuilds.

**Comment by deniszh** [comment]
Hi @christian-weiss ,

TBH, I completely lost point at this stage.

> You can configure the "link to github" at any time incl. on existing docker hub repos. 

Yes, but why should I do that?

> You can have multiple docker hub repos linked to a single github repo.

True, but that's a bad thing for our task, no? We should distinguish repos and not make them similar?

> And you can enable and disable "autobuild" for each docker hub repo independently from the other docker hub repos.

Yes, but how it's related to our problem?

> Please do the "link to github" procedure above for https://hub.docker.com/r/graphiteapp/graphite-statsd, even if you plan to do manual build and releases, instead of autobuilds.

Why? How will it help with issue above?

**Comment by deniszh** [comment]
Theoretically, there's not much sense in having autobuild enbled in separate repo. `graphiteapp/docker-graphite-statsd` has very low amount of downloads, I can simply remove it now.
Enabling autobuild in `graphiteapp/graphite-statsd` also not really useful, maybe we can have `master` branch build automatically for amd64 on every master push - releases should be build manually, because of arm builds.

**Comment by christian-weiss** [comment]
Thanks for implementing the procedure from above. "Dockerfile" page/tab and "link to github" is now available. 

I think i can we can close this ticket now, as its original target is resolved.

Feel free to file a github issue about more improvements (e.g. getting rid of docker-graphite-statsd,  implementing autobuild for stable-releases triggered by git tags, using docker hub autobuild to build multiarch docker images, etc.). I am willing to help.
