### ISSUE TITLE
Build multiarch docker images: provide an arm64/v8 image

### ISSUE THREAD

**Issue by christian-weiss** [graphite-project/docker-graphite-statsd#126]
ARM is an important architecture, empowering clouds (like AWS; cost savings about 45% are possible on AWS with ARM), RaspberryPi and tons of NAS systems, etc.

Please provide a multiarch docker image that includes arm64/v8.

This would enable me to run graphite-statsd on my QNAP NAS, as other stuff (like mariadb) already do.

It is as easy as running:
```
docker buildx build --platform linux/arm,linux/arm64,linux/amd64/v8 -t graphiteapp/docker-graphite-statsd . --push
```
Just follow the preparation steps described here:
https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/

Supported platform names are here:
https://github.com/docker-library/official-images#architectures-other-than-amd64

You are already using a docker base image (alpine) which is available as arm64/v8, so you are ready to go.

**Comment by deniszh** [comment]
Hello @christian-weiss !

Thanks for your suggestion. I build arm and arm64 version and pushed it to the repo. Will do that for new releases too.

For the record - command is `docker buildx build --platform linux/arm,linux/arm64,linux/amd64 -t graphiteapp/graphite-statsd:latest . --push`

**Comment by christian-weiss** [comment]
Fast. Perfect.
Now running on my QNAP NAS.
Thank you very very mutch.
