### ISSUE TITLE
Multiarch autobuild of graphiteapp/graphite-statsd

### ISSUE THREAD

**Issue by deniszh** [graphite-project/docker-graphite-statsd#128]
Ideally, we want:
- single github repo https://github.com/graphite-project/docker-graphite-statsd/
- single docker repo https://hub.docker.com/repository/docker/graphiteapp/graphite-statsd
- all pushes to master should  trigger build of latest image from master, tagging with `master` tag in docker hub, for amd64, arm and arm64 architectures
- making a release on github should trigger build of corresponding release for amd64, arm and arm64 architectures, marking them same tag as release, and also `latest`
- we should have a way to build image locally, at least for amd64

**Comment by deniszh** [comment]
See https://github.com/rmoriz/multiarch-test

**Comment by christian-weiss** [comment]
Maybe you want to join forces on implementing mutliarch builds on docker hub with: https://github.com/jjethwa/icinga2/issues/220 as it is on its way.

**Comment by christian-weiss** [comment]
https://github.com/rmoriz/multiarch-test is about the old approach, you may want to change the hooks to do "buildx" instead.

**Comment by daniela-waranie** [comment]
2 options:
a) wait for native support on docker hub (at least as docker hub experimental feature)
b) setup that stuff with hooks by yourself

There is a ticket for (a): https://github.com/docker/hub-feedback/issues/1874 feel free to vote.

**Comment by deniszh** [comment]
Implemented using Github Workflow - https://github.com/graphite-project/docker-graphite-statsd/tree/master/.github/workflows
