### ISSUE TITLE
[BUG] Issue with logrotate on graphite 1.1.7-2

### ISSUE THREAD

**Issue by nikobearrr** [graphite-project/docker-graphite-statsd#130]
**Describe the bug**
Logrotate does not seem to work on graphite

**To Reproduce**
I use graphite-statsd 1.1.7-2 with custom logrotate.conf
I build the image and I deploy it. When I check couple of days after I dont see the logs rotate

**Expected behavior**
I would expect to see the logs rotated

**Environment (please complete the following information):**

This is my docker file:

```
FROM graphiteapp/graphite-statsd:1.1.7-2

ADD storage-schemas.conf /opt/graphite/conf/
ADD carbon.conf /opt/graphite/conf/
ADD udp.js /opt/statsd/config/
COPY logrotate.conf /etc/logrotate.d/graphite-statsd
```

No mounted volumes to host.
The logrotate.conf I have is:

```
/var/log/*.log /var/log/*/*.log {
  daily
  size 100M
  missingok
  rotate 3
  compress
  delaycompress
  ifempty
  copytruncate
  dateext
  dateformat "%Y-%m-%d"
}

```

**Additional context**

When I open the container and check logs I see this:

```
/ # ls -l /var/log
total 11284
drwxr-xr-x    2 root     root          4096 Apr  6 19:48 carbon
-rw-r--r--    1 root     root          1496 Apr  8 00:32 carbon-aggregator.log
-rw-r--r--    1 root     root             0 Apr  8 00:32 carbon-relay.log
-rw-r--r--    1 root     root      10581438 Apr 11 09:12 carbon.log
drwxr-xr-x    2 root     root          4096 Apr 11 09:11 graphite
-rw-r--r--    1 root     root        934483 Apr 11 09:11 gunicorn.log
drwxr-xr-x    2 root     root          4096 Apr  8 00:32 nginx
drwxr-xr-x    2 redis    redis         4096 Apr  6 19:48 redis
-rw-r--r--    1 root     root           104 Apr  8 00:32 statsd.log
-rw-r--r--    1 root     root             0 Apr  8 00:32 syslog
```

When I run `logrotate -vf /etc/logrotate.d/graphite-statsd` the logroate starts

This is the result of the logs folder afterwards:

```
/ # ls -l /var/log
total 11276
drwxr-xr-x    2 root     root          4096 Apr  6 19:48 carbon
-rw-r--r--    1 root     root             0 Apr 11 09:12 carbon-aggregator.log
-rw-r--r--    1 root     root          1496 Apr 11 09:12 carbon-aggregator.log"2020-04-11"
-rw-r--r--    1 root     root             0 Apr 11 09:12 carbon-relay.log
-rw-r--r--    1 root     root             0 Apr 11 09:12 carbon-relay.log"2020-04-11"
-rw-r--r--    1 root     root             0 Apr 11 09:12 carbon.log
-rw-r--r--    1 root     root      10582171 Apr 11 09:12 carbon.log"2020-04-11"
drwxr-xr-x    2 root     root          4096 Apr 11 09:12 graphite
-rw-r--r--    1 root     root             0 Apr 11 09:12 gunicorn.log
-rw-r--r--    1 root     root        934483 Apr 11 09:12 gunicorn.log"2020-04-11"
drwxr-xr-x    2 root     root          4096 Apr 11 09:12 nginx
drwxr-xr-x    2 redis    redis         4096 Apr  6 19:48 redis
-rw-r--r--    1 root     root             0 Apr 11 09:12 statsd.log
-rw-r--r--    1 root     root           104 Apr 11 09:12 statsd.log"2020-04-11"
-rw-r--r--    1 root     root             0 Apr  8 00:32 syslog
/ #
```

Which works fine and I would expect that every day the logs are rotated. But that doesn't seem to be the case.

**Comment by deniszh** [comment]
TBH I'm a bit out of ideas here. If that would be permission issue like #111 - then manual run also should fail. Then, something wrong with a cron, maybe.
@nikobearrr : do you see some errors ion logs, like in #111 ?

**Comment by nikobearrr** [comment]
Hi @deniszh 
I do not see any errors. I actually suspect since I have put a custom logrotate that I have "broken it". I am not sure if that can be, but I am in the process of testing. 

The original /etc/logrotate.conf has a rotation weekly, whilst my /etc/logrotate.d/graphite-statsd has daily. My guess is that the /etc/logrotate.conf has somehow prevented running the graphite-statsd. I will update you with more information
