### ISSUE TITLE
Make tagging disabled through environment variable

### ISSUE THREAD

**Issue by deniszh** [graphite-project/docker-graphite-statsd#132]
Tagging is enabled for all metrics by default, which could cause performance issues.
So, it would be nice if possible to disable tagging in carbon.conf using some env variable (through ENABLE_TAGS = False)
Or, we can fix that solving https://github.com/graphite-project/carbon/issues/836

**Comment by nikolas** [comment]
Yes, and tagging is causing errors on my setup. Is there a more involved way to disable it?

**Comment by deniszh** [comment]
Fixed in #142, merged to master

**Comment by deniszh** [comment]
Released in [1.1.7-3](https://github.com/graphite-project/docker-graphite-statsd/releases/tag/1.1.7-3)
