### ISSUE TITLE
[BUG] Issues with using MySQL for the webapp

### ISSUE THREAD

**Issue by muhmud** [graphite-project/docker-graphite-statsd#133]
**Describe the bug**
When I use MySQL as the database for the webapp, everything works fine until I restart my graphite container, after which the webapp fails to start.

I think the issue is related to this line from the logs:
```
spawn /opt/graphite/bin/django-admin.py createsuperuser
```
Looking into the file `/etc/service/graphite/run`, the admin user is being created everytime if the sqlite database file does not exist.

**To Reproduce**
Use MySQL configuration for `DATABASES` in `local_settings.py` for the webapp and start the graphite container without the sqlite database file existing, then restart it. The webapp should give you connection refused.

**Expected behavior**
You should be able to restart the graphite container as required when using MySQL without needing the sqlite database file.

**Environment (please complete the following information):**
 - OS flavor: Amazon Linux 2
 - Image version: latest at time of writing
 - Custom volumes mounted: most of those given in the documentation

**Additional context**

**Comment by deniszh** [comment]
Yes, agreed, will fix it. Thanks for reporting!

**Comment by deniszh** [comment]
I hope fixed now, although a bit ugly

**Comment by deniszh** [comment]
Released in [1.1.7-3](https://github.com/graphite-project/docker-graphite-statsd/releases/tag/1.1.7-3)

**Comment by muhmud** [comment]
Thanks!

Will take a look when refresh my containers
