### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KhanHam** [graphite-project/docker-graphite-statsd#134]
**Describe the bug**

I am using this repo to create an image on container application platform (Openshift), but the build gets stuck on 
```COPY --from=build /opt /opt```

**To Reproduce**

1.Forked the repo to my organization.
2. Used the ssh link to build image on Openshift.

**Expected behavior**

The build should finish and push the image to registry.

**Comment by deniszh** [comment]
Hi @KhanHam ,
I'm afraid you need to open this issue with Openshift or find out what's wrong with your platform. 
There's nothing wrong with `COPY --from=build /opt /opt` command.
