### ISSUE TITLE
Carbon scaling

### ISSUE THREAD

**Issue by deniszh** [graphite-project/docker-graphite-statsd#135]
I noticed that somehow people using this container in quite loaded environments. While it has OKish defaults for graphite-web it uses only single `carbon` instance, which will not scale beyond single CPU core.
To overcome this you need quite non-trivial modification - enable relay, change port of carbon, create additional carbon configs, configure routing from relay to carbons, configure new carbon in graphite-web.
So, it would be nice if all these operation can be done easily, with settings some common variable, like `CARBON_CACHES=N`

(I'm hesitating to cheat with just `go-carbon` instead....)

**Comment by deniszh** [comment]
OK, I'm not really satisfied with results yet, so, will postpone up to next release

**Comment by nikobearrr** [comment]
Hey @deniszh. I came accross this issue and I would like to ask you how do you see a way to improve that? You have written that a carbon instance will use only 1 CPU. When running in a docker container how can we make the different carbon instances to use more cores? Would just creating 2-3 more carbon cache's and relaying the traffic to all of them make things perform much better?

**Comment by deniszh** [comment]
Hi @nikobearrr ,

That's a known issue about scaling Python programs over multiple CPUs. It's not exactly true, because carbon uses Twisted library for async processing, but, indeed, scaling Python programs can be tricky. 
It's not a news for Graphite, though - it's whole architecture was designed around it. We have `relay` to split metric stream to multiple carbon caches, and `graphite-web` knows in which cache it needs to look for data, so, it's doing that quite fast.
`relay` not doing disk IO, also using Twisted, but obviously it's a still python program, so, it has limited scalability too. So, when we need to scale relay itself - it can be done very easy, using some TCP load balancer, e.g. HaProxy.
So, we have classic 2-tiered architecture - HaProxy balances metric flow via N relays which balances it to M carbon caches, which are connected to graphite-web. 
But as you can see it has obvious downside - that setup it quite complex. It can handle quite serious metric flow, though, and usually people implementing this across bare metal servers with appropriate tuning. Also, please note that you'll benefit from that setup only if you have bottleneck on CPU in carbon-cache. It will not help with e.g. IO bottlenecks. Without CPU bottleneck it's not the fact that 2 carbon caches will be faster then single cache, probably whole setup maybe will be even slower.
And that's a question coming - do we really to go to that complex setup inside single Docker container, especially if it will help only with CPU scalability? Is it really possible / have sense to implement it here? Is it really possible to really hit python scalability bottleneck in that setup?
I have no answers on this questions, still.
Obviously, many other solutions/improvements can be done.
Simplest one - using `go-carbon`. I even added it to latest image as an experiment. It's much more scalable, so, probably, it will cover 99% of usecases of scalability of single Docker Graphite container.
Or you can still use multiple carbon-caches, but using scalable compatible relay  to route traffic (we have carbon-c-relay, written in C, graphite-relay-ng written in Go, etc) - then you removing haproxy and relay from setup. But it's kinda against an idea of whole project - we're ignoring python's relay completely, which is not good. Also all these relays not exactly compatible with original relay, and has completely different setup.

**Comment by nikobearrr** [comment]
Hey @deniszh, thanks for the thorough explanation. 
I see the issues of having the python as backend, but perhaps this is most of a question related to how will graphite move forward? Is there a plan to migrate the carbon (to go or other faster than python framework)? 
The only issue with go-carbon is that there is not only 1 (open-source) project of this type which of course leads to different implementations and will end up very different. 
I plan to give the one you bundled a go in the upcoming months (general testing, performance) to see how it compares with the default python implementation

**Comment by Cactusbone** [comment]
We've been using pypy for carbon and graphite for a few years with some load without hitting the single CPU core limit.
However when switching to this image (without pypy), we've hit it instantly. 

I guess it will not hold with more load, but it can reduce this problem, without switching to go-carbon.

I'll open a PR with pypy soon (although the base alpine image made this more challenging), still under testing right now.

**Comment by deniszh** [comment]
For the record - pypy variant of image is included now.
