### ISSUE TITLE
[BUG] Auto-deploy new configs on run if they don't exist

### ISSUE THREAD

**Issue by mzealey** [graphite-project/docker-graphite-statsd#140]
**Please open bug only for Docker component here, if you want to do so for Graphite, please use [graphite-web repo](https://github.com/graphite-project/graphite-web/issues/new/choose)**

**Describe the bug**
I updated to :latest and tried using carbon-go via env variable. However it didn't work because https://github.com/graphite-project/docker-graphite-statsd/blob/master/conf/opt/graphite/conf/go-carbon.conf was not deployed. I am using persistent volumes.

I believe there should be a check of all config files at container startup & if they do not exist they should be created.

**Comment by deniszh** [comment]
Should be fixed in https://github.com/graphite-project/docker-graphite-statsd/pull/141

**Comment by deniszh** [comment]
Released in [1.1.7-3](https://github.com/graphite-project/docker-graphite-statsd/releases/tag/1.1.7-3)
