### ISSUE TITLE
[Q] Unable to login to Graphite Docker  Container

### ISSUE THREAD

**Issue by spcnvdr** [graphite-project/docker-graphite-statsd#146]
**Please ask questions only for Docker component here, if you want to do so about Graphite, please use [graphite-web repo](https://github.com/graphite-project/graphite-web/issues/new/choose)**

I am having trouble logging in to both Graphite and the Django Admin interface. I have tried the instructions provided in the README.md. Using the credentials root:root fails as does every other common default login I could find. Is there any additional documentation I missed or is there some sort of setup I am missing? 

I have had this issue running on a CentOS server and a Xubuntu desktop. I have also tried logging in from the same host as the Graphite Docker container and remotely from a different host and neither worked. All I am doing is installing Docker on the respective Linux OS, and running the command from the README.md file which is 

    sudo docker run -d\
     --name graphite\
     --restart=always\
     -p 80:80\
     -p 2003-2004:2003-2004\
     -p 2023-2024:2023-2024\
     -p 8125:8125/udp\
     -p 8126:8126\
     graphiteapp/graphite-statsd

Once Graphite is running, the login credentials fail on the page at:

    http://localhost/account/login 

and when clicking login link from the default page. 
I would appreciate any help with this issue. Thank you for your help and for providing awesome software.

**Comment by deniszh** [comment]
It's regression introduced in https://github.com/graphite-project/docker-graphite-statsd/pull/136 and released in 1.1.7-3 and fixed in https://github.com/graphite-project/docker-graphite-statsd/pull/145
You can use 1.1.7-2 or master tag for now, fix will be released in 1.1.7-4 soon.

**Comment by spcnvdr** [comment]
Okay, thank you.

**Comment by deniszh** [comment]
I hope I finally fixed this and similar issues in 1.1.7-5. Nothing potentially interesting happened in between, so, you can stay on 1.1.7-2, if you want.
