### ISSUE TITLE
[Q] I'm confused about WSGI configuration

### ISSUE THREAD

**Issue by Cactusbone** [graphite-project/docker-graphite-statsd#150]
From https://github.com/graphite-project/docker-graphite-statsd#tunables

It says default worker type is "sync" and "threads" is set to 2. but [gunicorn doc](https://docs.gunicorn.org/en/stable/settings.html#threads) says when threads is above 1, if worker type is "sync", it uses "gthread" worker type.

From https://github.com/graphite-project/docker-graphite-statsd/blob/master/conf/etc/service/graphite/run
default GRAPHITE_WSGI_THREADS is 1 and not 2, so the documentation might be in need of update.

**Comment by deniszh** [comment]
Yes, GRAPHITE_WSGI_THREADS by default set to 1, so, tunables section needs to be updated.

**Comment by deniszh** [comment]
Fixed

**Comment by Cactusbone** [comment]
Thx ! :)
