### ISSUE TITLE
[BUG]  Code for sending fake stats in the example is not correct. 

### ISSUE THREAD

**Issue by slash5toaster** [graphite-project/docker-graphite-statsd#153]
**Describe the bug**
 Code for sending fake stats in the example is not correct. 

**To Reproduce**

run the example code 
``` while true; do echo -n "example:$((RANDOM % 100))|c" | nc -w 1 -u 127.0.0.1 8125; done``` 
no stats show up 

**Expected behavior**
Stats show in the browser

**Environment (please complete the following information):**
 - OS flavor: MacOS
 - Image version 1.1.7-6
 - Custom volumes mounted:  none

**Additional context**

It appears `bc` was typed as `c`
```
while true; do echo -n "example:$((RANDOM % 100))| bc" | nc -w 1 -u 127.0.0.1 8125; done

```

**Comment by piotr1212** [comment]
I think the first one is correct.

**Comment by piotr1212** [comment]
Also see https://github.com/statsd/statsd#usage

**Comment by deniszh** [comment]
I think issue above is with some version of MasOS `nc` - https://github.com/graphite-project/docker-graphite-statsd/issues/37
