### ISSUE TITLE
[Q] logrotate and GRAPHITE_LOG_ROTATION option ?

### ISSUE THREAD

**Issue by Cactusbone** [graphite-project/docker-graphite-statsd#157]
I'm not sure how python rotates logs, but on my own, i have like 2 minutes of graphites logs and no usefull rotation...
since logrotate is enabled, shouldn't GRAPHITE_LOG_ROTATION be false by default ?

graphite [own documentation](https://graphite.readthedocs.io/en/latest/releases/1_0_0.html?highlight=LOG_ROTATION#other-changes) says 
> Python’s own log rotation can be disabled using the LOG_ROTATION setting. This is useful when running multiple WSGI workers.

How is it supposed to work ? :)

**Comment by Cactusbone** [comment]
by setting GRAPHITE_LOG_ROTATION to false, logrotate does indeed start rotating logs, so it should be the default value imho, to be able to configure all log rotation in a single place (logrotate configuration file)

**Comment by deniszh** [comment]
Yes, you probably right, we need to change defauly in this setup at least.

**Comment by deniszh** [comment]
Fixed in [1.1.7-9](https://github.com/graphite-project/docker-graphite-statsd/releases/tag/1.1.7-9)
