### ISSUE TITLE
[Q]couldn't verify which carbon I'm using

### ISSUE THREAD

**Issue by hritz220** [graphite-project/docker-graphite-statsd#161]
I want to use go-carbon, I tried following command:
 `docker run -d --name graphite --restart=always -p 80:80 -p 2003-2004:2003-2004 -p 2023-2024:2023-2024 -p 8125:8125/udp -p 8126:8126 graphiteapp/graphite-statsd -e "GOCARBON=1"
`
how can I verify that I'm  using go-carbon  instead of carbon ?

**Comment by piotr1212** [comment]
check processlist: `ps -ef | grep carbon`

**Comment by deniszh** [comment]
@hritz220 : you didn't using GOCARBON environment variable in second case. You need to use `-e` flag for docker to do so:
```bash
docker run -d --name graphite --restart=always -p 80:80 \
   -p 2003-2004:2003-2004 \
   -p 2023-2024:2023-2024 \
   -p 8125:8125/udp -p 8126:8126 \
   -e "GOCARBON=1" \
  graphiteapp/graphite-statsd 
```

**Comment by hritz220** [comment]
@deniszh 
Hey I tried the command you provided, here's the log output:
```
[root@ip-172-31-81-35 docker-graphite-statsd]# docker run -d --name graphite --restart=always -p 80:80 \
>    -p 2003-2004:2003-2004 \
>    -p 2023-2024:2023-2024 \
>    -p 8125:8125/udp -p 8126:8126 \
>    -e "GOCARBON=1" \
>   graphiteapp/graphite-statsd 
63d53452dc54e375e1669a0e86edcee49ba7a0546112b2ee4f82435aebe28106
[root@ip-172-31-81-35 docker-graphite-statsd]# ps -ef | grep carbon
root      3611  3608  0 18:35 ?        00:00:00 runsv carbon
root      3612  3608  0 18:35 ?        00:00:00 runsv carbon-aggregator
root      3613  3608  0 18:35 ?        00:00:00 runsv carbon-relay
root      3616  3608  0 18:35 ?        00:00:00 runsv go-carbon
root      3622  3616  3 18:35 ?        00:00:00 /opt/graphite/bin/go-carbon -config=/opt/graphite/conf/go-carbon.conf -daemon=false
root      3630  3613  0 18:35 ?        00:00:00 tee -a /var/log/carbon-relay.log
root      3632  3612  0 18:35 ?        00:00:00 tee -a /var/log/carbon-aggregator.log
root      3637  3611  0 18:35 ?        00:00:00 tee -a /var/log/carbon.log
root      3752   875  0 18:35 pts/0    00:00:00 grep --color=auto carbon

```
How will I verify go-carbon is running, I can see in the logs "runsv go-carbon", but I can see it when I'm not using "GOCARBON=1" ?

**Comment by deniszh** [comment]
Next command after runsv says


00:00:00 /opt/graphite/bin/go-carbon
-config=/opt/graphite/conf/go-carbon.conf -daemon=false

That’s go-carbon process running.

**Comment by hritz220** [comment]
@deniszh 
If you can see in CASE1, you will found runsv go-carbon, I want to know why it is present in CASE1, please let me know.

**Comment by deniszh** [comment]
Sorry, I didn’t understand your question, could you please elaborate? Or
maybe explain what you trying to achieve?

**Comment by hritz220** [comment]
@deniszh I'm trying to use go-carbon but I can see "runsv go-carbon", in both cases whether I'm using environment variable "GOCARBON=1" or not, just confused why runsv go-carbon is present in both cases.

**Comment by deniszh** [comment]
That’s how svinit works. You can grep for full path of process, I.e. ‘ps
-ef | grep /opt/graphite/bin/go-carbon’ to avoid confusion.
