### ISSUE TITLE
[Q] Migrate tag data from sqlite to redis

### ISSUE THREAD

**Issue by TomKeyte** [graphite-project/docker-graphite-statsd#163]
Is it possible to migrate the tag data from sqlite to redis?

My sqlite DB has reached 1.7GB (and growing) which is leading to performance issues

Unfortunately, when setting up, this wasn't configured, however, the historic tag data is still required. Is it possible to migrate data from sqlite to redis

Thanks

**Comment by deniszh** [comment]
@TomKeyte : That's should be technically possible, but I'm afraid we have no ready to use tooling yet. Let me check the code, maybe we can come up with some simple script.

**Comment by TomKeyte** [comment]
Thanks @deniszh that would be very helpful

**Comment by deniszh** [comment]
Hi @TomKeyte ,

I'm looking for options how we could implemen it. One way - having some sort of combined TagDB, which will read from both Redis and SQL, then you can switch TagDB to Redis in carbon and everything will work flawlessly. That's probably best solution, but implementing some cleanup logic will make it much more complex.
Or we can make some quick migration script, then you can copy DB from live graphite, put it into script and it will migrate existing tags to redis. Then you should switch both carbon and graphite web to Redis. But this way will require some downtime or you can potentially loose some tags during migration. Also it will not work with built-in redis in Docker image...
