### ISSUE TITLE
arm image fails to run

### ISSUE THREAD

**Issue by antonpiatek** [graphite-project/docker-graphite-statsd#169]
I'm struggling to get the arm image to work, is it built correctly as it appears to be an incompatible architecture for a raspberry pi 4:

    $ docker pull graphiteapp/graphite-statsd; docker run --rm -it graphiteapp/graphite-statsd
    Using default tag: latest
    latest: Pulling from graphiteapp/graphite-statsd
    Digest: sha256:da0cbe12ae30e677d5b0d7411f725e90432c703994e90835c34cc3de5df10fa2
    Status: Image is up to date for graphiteapp/graphite-statsd:latest
    Started runsvdir, PID is 46
    wait for processes to start....
    /usr/sbin/crond 4.5 dillon's cron daemon, started with loglevel notice
    Fatal Python error: pyinit_main: can't initialize time
    Python runtime state: core initialized
    PermissionError: [Errno 1] Operation not permitted
    
    Current thread 0xb6f8f390 (most recent call first):
    <no Python frame>
    Fatal Python error: pyinit_main: can't initialize time
    Python runtime state: core initialized
    PermissionError: [Errno 1] Operation not permitted

(this error just repeats)

Docker reports it in linux/arm so I thought this matches the published images?

    $ docker version
    Client:
     Version:           18.09.1
     API version:       1.39
     Go version:        go1.11.6
     Git commit:        4c52b90
     Built:             Fri, 13 Sep 2019 10:45:43 +0100
     OS/Arch:           linux/arm
     Experimental:      false
    
    Server:
     Engine:
      Version:          18.09.1
      API version:      1.39 (minimum version 1.12)
      Go version:       go1.11.6
      Git commit:       4c52b90
      Built:            Fri Sep 13 09:45:43 2019
      OS/Arch:          linux/arm
      Experimental:     false

**Comment by deniszh** [comment]
Hi @antonpiatek ,

Unfortunately, I have no RPi4 to test, also, even if able to reproduce  - I have no idea how to fix. I build ARM image using same Dockerfile using docker buildx. Please note that we're building linux/arm/v7 and linux/arm64 images only, maybe RPi not support that? My quick googling didn't show relevan answer which architecture RPi docker uses....

**Comment by antonpiatek** [comment]
Not sure - I think it is supposed to be arm/v7 by default on a raspberry pi 4. I also know other images aimed at arm/v6 have to to more effort to work and can't use the auto-detect so publish specialised tags for docker builds on that architecture (but arm is a bigger target for them)

I actually got the feeling from general research that am64 is more prevalent so have reinstalled my pi to use the arm64 ubuntu image rather than raspbian and that works.

Guess the issue probably still exist, and I've no better understanding of how buildx targets platforms for build, nor how docker lines them up (does arm definitely default to armv7 (and is a pi4 definitely armv7?)), but if anyone hits the same issue I can say that arm64 works.
