### ISSUE TITLE
[Q] StatsD bypasses the aggregator & relay and writes to the cache instance instead, is this correct?

### ISSUE THREAD

**Issue by simtr** [graphite-project/docker-graphite-statsd#173]
**Please ask questions only for Docker component here, if you want to do so about Graphite, please use [graphite-web repo](https://github.com/graphite-project/graphite-web/issues/new/choose)**

StatsD bypasses the aggregator & relay and writes to the cache instance instead, is this correct?

I have a bunch of stats coming into 8125 UDP from a few collectors, the collector I'm using doesn't let me configure the stats and naming I want, so I was trying to set up some blacklisting & rewrite rules, which I had configured on the aggregator (`USE_WHITELIST` set to `True` in `carbon.conf` under `[aggregator]` and rules added to `rewrite-rules.conf`)

These weren't working, and I was slowly going insane, double, triple, quadruple checking my regexes.

I took a closer look at the configuration that the container generated for me:
carbon.conf:
```
[cache]
...
LINE_RECEIVER_PORT = 2003
...
UDP_RECEIVER_PORT = 2003

[aggregator]
...
LINE_RECEIVER_PORT = 2023
...
PICKLE_RECEIVER_PORT = 2024

```

statsd/udp.js
```
{
  "graphiteHost": "127.0.0.1",
  "graphitePort": 2003,
  "port": 8125,
  "flushInterval": 10000,
  "servers": [
    { server: "./servers/udp", address: "0.0.0.0", port: 8125 }
  ]
}
```

I noticed that the stats being written by the StatsD instance inside the container were going straight to the cache instead of passing through the aggregator.

I changed the `"graphitePort"` to 2023, and now my stats are being filtered & rewritten.

So, am I using this incorrectly (i.e is it wise to put statsd data through the aggreator) or is this some undocumented (or documented and I missed it) config?

**Comment by deniszh** [comment]
Hi @simtr ,

Yes, you're right, Statsd going directly to carbon. Aggregator performance is not that great, and can become an issue - that's one of the reasons for this. But if you fixed that correctly - by re-pointing it to aggregator port.

**Comment by simtr** [comment]
Thanks for clearing that up for me 😃
