### ISSUE TITLE
Unable to save dashboard: htmlEncode is not defined

### ISSUE THREAD

**Issue by bobemoe** [graphite-project/docker-graphite-statsd#181]
Using latest docker image `graphiteapp/graphite-statsd`, I can compose a dashboard, but when I come to save it it is not saved, in console I see:
```
Uncaught ReferenceError: htmlEncode is not defined
    setDashboardName https://mydomain.co.uk/static/js/dashboard.js:3012
    saveDashboard https://mydomain.co.uk/static/js/dashboard.js:2723
    createDelegate https://mydomain.co.uk/static/js/ext/adapter/ext/ext-base.js:7
``` 
Everything else seems to be working fine, can collect data, compose graphs, save graphs, even save dashboard templates, just can't save an actual dashboard.

**Comment by deniszh** [comment]
Yes, that's a known issue. Will be fixed in next release, I hope - soon

**Comment by BastienDurel** [comment]
As a temporary fix, you should add 
```
var htmlEncode = htmlEncode || Ext.util.Format.htmlEncode;
var newURL = newURL || null;
```
in `dashboard.js`

Or add a userscript to your browser, [like this](https://gist.github.com/BastienDurel/065ca67182c77f2c9cacffdafdd82a1f)

**Comment by bobemoe** [comment]
Just updated to 1.1.8-8 and tested this again, it is now working correctly.

Thanks :)
