### ISSUE TITLE
[BUG] AttributeError: 'ParseResults' object has no attribute 'raw'

### ISSUE THREAD

**Issue by grosserg** [graphite-project/docker-graphite-statsd#182]
Related to the issue https://github.com/graphite-project/graphite-web/issues/2726

The issue is still reproduced in the docker version.

**Environment:**
 - OS: Ubuntu 20.04.3
 - Image version 1.1.6-1 - 1.1.8-2

**Additional context**
It works if only I add `&& pip3 install --no-deps --force-reinstall pyparsing==2.4.7 \`
 after the line https://github.com/graphite-project/docker-graphite-statsd/blob/2c089d19c259d57e1da1d506e63c6c5db3e8227d/Dockerfile#L107

**Comment by salavessa** [comment]
I started to get this error after updating from `1.1.8-2-pypy` to `1.1.8-4-pypy`.
Probably not relevant but graphite is being queried by grafana.
Reverting back to `1.1.8-2-pypy` got things working again.

**Comment by deniszh** [comment]
Ah, indeed, forgot to pin pyparsing for now. Will release 1.1.8-5 today

**Comment by deniszh** [comment]
Sorry for delay, 1.1.8-5 is released, images come shortly.

**Comment by dkozinn** [comment]
I've pulled the new image (ARM64 in my case) and can confirm the issue is resolved for me.

**Comment by deniszh** [comment]
Thanks! Will close it after release of 1.1.9
