### ISSUE TITLE
Build for linux/arm64/v8

### ISSUE THREAD

**Issue by hingston** [graphite-project/docker-graphite-statsd#190]
**Please open feature request only for Docker component here, if you want to do so for Graphite, please use [graphite-web repo](https://github.com/graphite-project/graphite-web/issues/new/choose)**

**Is your feature request related to a problem? Please describe.**
Currently you have to run this image on m1 chip macs in emulation mode. This is much slower.

**Describe the solution you'd like**
Please offer a build for linux/arm64/v8

**Describe alternatives you've considered**
You can currently run the image with docker's experimental emulation feature enabled. This is slow.

**Additional context**

**Comment by deniszh** [comment]
Hmmm... I was assuming that linux/arm64 is alias for linux/arm64/v8 
Ok, then it's better instead of `linux/arm,linux/arm64` use something like `linux/arm/v7,linux/arm64/v8`

**Comment by deniszh** [comment]
Ok, at least it's buildable (I have no m1 and build in quemu took almost 4 hours, geez). Will do PR and release soon.

**Comment by deniszh** [comment]
Will change arm64/v7 to arm64/v8 in 1.1.9, awaiting it next week or so.

**Comment by deniszh** [comment]
Released 1.1.8-8 with v8 support
