### ISSUE TITLE
[BUG] Trace logging is on by default

### ISSUE THREAD

**Issue by jdmarshall** [graphite-project/docker-graphite-statsd#191]
**Please open bug only for Docker component here, if you want to do so for Graphite, please use [graphite-web repo](https://github.com/graphite-project/graphite-web/issues/new/choose)**

**Describe the bug**
Nobody needs to see every time a client connects to graphite is opened and closed. This is trace-level information and should be off by default

**To Reproduce**
Run docker-graphite-statsd, and watch the screen scroll and scroll.

**Expected behavior**
Error logging to console, and not much else.

**Environment (please complete the following information):**
 Straight out of the box.
 
**Additional context**
I'm trying to run this in docker-compose, and I can't read any logs from my apps because graphite is scrolling the window every fifteen seconds:

28/01/2022 01:22:55 :: [listener] MetricLineReceiver connection with 127.0.0.1:46950 established

**Comment by deniszh** [comment]
Hi @jdmarshall ,
I'll test if `LOG_LISTENER_CONN_SUCCESS=False` fixing issue, will change default then in next release.

**Comment by jdmarshall** [comment]
It did not for me.  I think the conversation elsewhere is that the problem is in the config file, and that the python code is not evaluating environment variables during initialization.

**Comment by deniszh** [comment]
Yes, I mean config variable, not env variable. You’re right that it should
not be enabled by default

**Comment by deniszh** [comment]
Fixed in 1.1.8-6, image will be ready in couple of hours (as automation build it).

**Comment by deniszh** [comment]
Correction - in 1.1.8-7
