### ISSUE TITLE
[BUG] Unable to create image on Oracle Linux 8 on Windows 11 Virtual Box 6.1.x 

### ISSUE THREAD

**Issue by DineshGuptaa** [graphite-project/docker-graphite-statsd#202]
**Describe the bug**
I Just cloned the project and run the command `docker build .` and got the below error

**To Reproduce**
Just run the `docker build .`

**Expected behaviour**
I mages should be created on the Linux system

**Environment (please complete the following information):**
 - OS flavor: Oracle LInux 8 on Windows 11 Virtual Box 6.1.x 
 - Image version: master branch

**Additional context**

While trying to create docker build images got an error

    Removing intermediate container 2c7be38fe698
	 ---> 340c8f9b15f2
	Step 16/48 : ARG carbon_version=${version}
	 ---> Running in b84022b86ed4
	Removing intermediate container b84022b86ed4
	 ---> 303f7934f920
	Step 17/48 : ARG carbon_repo=https://github.com/graphite-project/carbon.git
	 ---> Running in e77e49f4ba27
	Removing intermediate container e77e49f4ba27
	 ---> ae38943e4e84
	Step 18/48 : RUN . /opt/graphite/bin/activate  && git clone -b ${carbon_version} --depth 1 ${carbon_repo} /usr/local/src/carbon  && cd /usr/local/src/carbon  && pip3 install -r requirements.txt  && python3 ./setup.py install $python_extra_flags
	 ---> Running in e423dcbc5652
	Cloning into '/usr/local/src/carbon'...
	Note: switching to '855218e3f333dde49533389b2e85bc2d1421d43c'.

	You are in 'detached HEAD' state. You can look around, make experimental
	changes and commit them, and you can discard any commits you make in this
	state without impacting any branches by switching back to a branch.

	If you want to create a new branch to retain commits you create, you may
	do so (now or later) by using -c with the switch command. Example:

	  git switch -c <new-branch-name>

	Or undo this operation with:

	  git switch -

	Turn off this advice by setting config variable advice.detachedHead to false

	Collecting whisper
	  Cloning git://github.com/graphite-project/whisper.git to /tmp/pip-install-pvo1fwmt/whisper_6d7c56e0666f4c1f827229b34afe5b6b
	  Running command git clone --filter=blob:none --quiet git://github.com/graphite-project/whisper.git /tmp/pip-install-pvo1fwmt/whisper_6d7c56e0666f4c1f827229b34afe5b6b
	  fatal: remote error:
		The unauthenticated git protocol on port 9418 is no longer supported.
	  Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
	  error: subprocess-exited-with-error
	  
	  × git clone --filter=blob:none --quiet git://github.com/graphite-project/whisper.git /tmp/pip-install-pvo1fwmt/whisper_6d7c56e0666f4c1f827229b34afe5b6b did not run successfully.
	  │ exit code: 128
	  ╰─> See above for output.
	  
	  note: This error originates from a subprocess, and is likely not a problem with pip.
	error: subprocess-exited-with-error

	× git clone --filter=blob:none --quiet git://github.com/graphite-project/whisper.git /tmp/pip-install-pvo1fwmt/whisper_6d7c56e0666f4c1f827229b34afe5b6b did not run successfully.
	│ exit code: 128
	╰─> See above for output.

	note: This error originates from a subprocess, and is likely not a problem with pip.
	The command '/bin/sh -c . /opt/graphite/bin/activate  && git clone -b ${carbon_version} --depth 1 ${carbon_repo} /usr/local/src/carbon  && cd /usr/local/src/carbon  && pip3 install -r requirements.txt  && python3 ./setup.py install $python_extra_flags' returned a non-zero code: 1
	ERROR: Service 'statsd' failed to build : Build failed

**Comment by deniszh** [comment]
Confirmed. Fixed in master, it's buildable now with `docker build -t graphiteapp/graphite-statsd . --build-arg version=master --build-arg python_binary=python3`
Will bi fixed in 1.1.9 release.

**Comment by DineshGuptaa** [comment]
Thanks, deniszh !!!
   Please help me with where needs to be modified in the `docker-compose.yml` so that, can be combined with `Grafana`. I want to use graphite with Grafana.

**Comment by deniszh** [comment]
Sorry, @DineshGuptaa , that's outside of purpose of this repo. You can use e.g.  some articles for that - https://www.theairtips.com/post/setting-up-grafana-with-docker-compose
