### ISSUE TITLE
Tweak collectd monitoring so that disk free reports actually work

### ISSUE THREAD

**Issue by SJrX** [graphite-project/docker-graphite-statsd#207]
**Is your feature request related to a problem? Please describe.**
A year ago I opened #176 , but I never got around to doing it. Essentially we run out of disk space and that can be suboptimal. Collectd can report disk space metrics, but the config is invalid.

In #176 I had a complex solution, but there is a trivial one where we can just tweak the config.

**Describe the solution you'd like**
Report disk metrics for /

**Describe alternatives you've considered**
A complex system of env vars, also supplying additional configuration files.

**Additional context**
N/A

The MR _might_ break anyone who actually has a `/dev/vda`  device, but I think that's few and far between when running in docker.

**Comment by SJrX** [comment]
The MR is a low risk change, but I didn't actually test it because it's blocked by #205 .

**Comment by deniszh** [comment]
Merged both fixes for #205 and #207
