### ISSUE TITLE
Enable AMQP by Default

### ISSUE THREAD

**Issue by EstebanBorai** [graphite-project/docker-graphite-statsd#219]
Hi! Im using this image to work with Graphite my goal is to feed the database
using AMQP, I noticed that by default AMQP is not enabled, it is possible to enable
AMQP by default using this image?

Looking through settings on: https://github.com/graphite-project/docker-graphite-statsd#tunables
I didn't found any environment variables related to AMQP.

Thanks in advance!

**Comment by deniszh** [comment]
Hi @EstebanBorai ,

Not sure if enabling AMQP by default is a good idea, but we can make it configurable, indeed.

**Comment by EstebanBorai** [comment]
Thanks for the quick response @deniszh! 

Making it configurable would be great! What Im doing today is manually edit the `carbon.conf` file using the Docker volume after the first run, and then I restart the container.

So having an environment variable like `AMQP_ENABLED` would be awesome. Other AMQP params such as host, port, user, password as environment variables would also come handy, this way we can spin up the container with the configuration on the first run!

**Comment by deniszh** [comment]
Fixed in #220 
New release baked in #221, should be available soon.

**Comment by EstebanBorai** [comment]
Thanks a lot @deniszh!
