### ISSUE TITLE
Make cross-origin URLs for django configurable

### ISSUE THREAD

**Issue by geekbeast** [graphite-project/docker-graphite-statsd#24]
By default the nginx configuration shipped in the docker container returns "*" for  theAccess-Control-Allowed-Origin header. This is a problem when using using include credentials as part of AJAX request since a specific host must be returned. The net effect is that authenticated cross-origin requests from grafana to graphite fail.

It looks like graphite already exposes this via **ALLOWED_HOSTS** (https://graphite.readthedocs.io/en/latest/config-local-settings.html#general-settings) but this isn't easy to access without doing a lot of work on the container itself.

I was able to work around this since I was using another nginx instance as we're running grafana/graphite on the same box, but I had to install nginx-extras and use more_set_headers to override the headers being returned to the correct value, but just based off what I saw from doing Google searches a lot of folks people will be prone to just echoing back the origin url and giving themselves XSS vulnerabilities .

If there is an easy way to do this would love a pointer to the docs :)

**Comment by deniszh** [comment]
Nginx config lives in own volume (`/etc/nginx`), so it can be overridden by mounting it - and I can add `nginx-extras` package to image. Should be enough.
