### ISSUE TITLE
add a new func in movingwindow

### ISSUE THREAD

**Issue by codexiao** [graphite-project/docker-graphite-statsd#25]
Hi, 

I'm trying to add a p90 "feature" under graphite-web/graphite/render/functions.py movingWindow function, and then make it a docker image (in the Dockerfile by only changing the graphite git-repo to point to my fork, where i only added following lamda p90 funciton below).  

aggFuncs = {
  'average': safeAvg,
  'median': safeMedian,
  'sum': safeSum,
  'min': safeMin,
  'max': safeMax,
  'diff': safeDiff,
  'stddev': safeStdDev,
  'count': safeLen,
  'range': lambda row: safeSubtract(safeMax(row), safeMin(row)),
  'multiply': lambda row: safeMul(*row),
  'p90': lambda row: _getPercentile(row, 90), <<<<<<------------ my added line
  'last': safeLast,
}

However, trying to call this function from Grafana gives me following error:
------------------------------
 File "/opt/graphite/webapp/graphite/render/functions.py", line 1050, in movingWindow
    raise Exception('Unsupported window function: %s' % (func))
Exception: Unsupported window function: p90
------------------------------

I then checked the mentioned functions.py in the docker but didn't see my p90 function. 

--------------------------------
docker exec d8a5149f4c8b cat /opt/graphite/webapp/graphite/render/functions.py > func_test.txt
--------------------------------

So, am i doing this right? Or, I"m being too naive here? What's the right way to add a p90 function? 

Thanks!

**Comment by deniszh** [comment]
No, looks like you're not doing this right. Try to implement "p90" as official custom function as described in https://graphite.readthedocs.io/en/latest/functions.html#function-plugins
Use current master branch for Graphite, it's not in docker yet. Official release will be in couple of days.

**Comment by codexiao** [comment]
@deniszh Thanks again, Denis!

I will give it a try. So, my goal is to call this p90 function from the movingWindow official function. It's doable right? like: movingWindow(myseries, '5min', 'p90'). 

And i would like to run it in a docker. Are following the right steps? 
1). write the p90 function.
2). cp it to /opt/graphite/webapp/graphite/functions/custom in container made from graphiteapp/graphite-statsd:1.0.2-3
3). make changes to FUNCTION_PLUGINS in the graphite settings. 

Thank you

**Comment by deniszh** [comment]
Almost.
>2). cp it to /opt/graphite/webapp/graphite/functions/custom in container made from graphiteapp/graphite-statsd:1.0.2-3

will not work - there's no custom functions support in 1.0.2-3
You need to build own docker image from master using `docker build -t graphiteapp/graphite-statsd . --build-arg version=master` or wait until 1.1.0 will be released (couple if days, I think).

**Comment by codexiao** [comment]
Got it. Thanks! I will try it and report back. 👍 . First I'll have to read about how to write this p90 customize function and make it callable by movingWindow. And then build the docker. 

Xiao Wang

**Comment by codexiao** [comment]
@deniszh I read about the link you shared earlier (https://graphite.readthedocs.io/en/latest/functions.html#function-plugins), but still couldn't sort it out how to apply to my case.  Can you help give more guidance?

I would like to utilize existing built-in movingWindow function. https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.movingWindow

But, make it call my customized p90 function to get the percentile 90 value. Goal would be like: movingWindow(someseries, '5min', 'p90').

If I use the function plugin, what should I write/define there? My understanding is that my p90 is just simple lambda calling existing built-in _getPercentile(row, 90) function?  

Also, if you have time, can you help also explain why adding 
'p90': lambda row: _getPercentile(row, 90), 
in the aggFuncs won't work?  (mentioned in my question at the very beginning) Seems like that's where the built-in movingWindow function uses?

Thanks a lot!!!

**Comment by deniszh** [comment]
@codexiao:
Yes, you're right! Sorry for misleading you.
Your fix should work. Fork giraphite-web repo, add `p90` lambda to [argFuncs dict](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L222-L234
), commit the change and then build own image using something like
```
docker build -t forked/graphite-statsd . --build-arg version=[master] --build-arg graphite_repo=[https://github.com/forked/graphite-web.git]
```
 where
[master] - your branch
[https://github.com/forked/graphite-web.git] - URL of your fork.

**Comment by codexiao** [comment]
@deniszh Thanks. I tried it. But calling it from Grafana, movingWindow(someseries, '5min', 'p90'), gave me following error. 

-----------------------------------------
File "/opt/graphite/webapp/graphite/render/functions.py", line 1050, in movingWindow
raise Exception('Unsupported window function: %s' % (func))
Exception: Unsupported window function: p90
-----------------------------------------

Feels like we also have to modify something elsewhere? 

Thank you

**Comment by deniszh** [comment]
You also mentioned that you do not see your change in the docker container. Is it still the case?

**Comment by deniszh** [comment]
Also master branch code does not contain movingWindow  function [in line 1050 of functions.py](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L1050). So, looks like you didn't build image properly.

**Comment by codexiao** [comment]
@deniszh ummm... sorry, i'm a bit lost. I forked graphite-project/graphite-web just two days ago. And under my forked version, I do see movingWindow at graphite-web/webapp/graphite/render/functions.py

At the same time two days ago, I also forked graphite-project/docker-graphite-statsd, and then made following change:
ARG graphite_repo=https://github.com/codexiao/graphite-web.git

And then I use "docker build -t customized_graphite . "

Seems like, mine does the same as yours? Something I missed?

I will also try your command later and update you. 

Thank you

**Comment by deniszh** [comment]
Try to make the customized build as described in my comment and check that your change is really propagated to running instance - then it should work.

**Comment by codexiao** [comment]
@deniszh It's working! Once again, you are awesome! Thanks for your help!!!

just curious, do you know why changing the Dockerfile doesn't work? But following your cli command works? 

-ARG graphite_repo=https://github.com/graphite-project/graphite-web.git
+ARG graphite_repo=https://github.com/codexiao/graphite-web.git

**Comment by deniszh** [comment]
No, sorry, @codexiao, changing Dockerfile should also work (but of course you need to rebuild image and running your rebuilded image instead)
