### ISSUE TITLE
Disable nginx

### ISSUE THREAD

**Issue by benhartwich** [graphite-project/docker-graphite-statsd#26]
Hi,

how can I disable the docker nginx and use my own installed nginx as proxy?

Regards,

**Comment by deniszh** [comment]
I do not think it's possible with a current image. Graphite itself is listening on 127.0.0.1:8080, I can map this port, of course - but Nginx not only proxying requests, but also serves static (CSS/JS) requests. 
Why not proxy to internal Nginx?

**Comment by benhartwich** [comment]
I´m running a nginx on the same machine, so I don´t need another nginx at all. So I´ve to use another port for docker nginx?

**Comment by deniszh** [comment]
As I said internal Nginx also serving static requests, you can't simply bypass it.

**Comment by deniszh** [comment]
But, I'm afraid, I'm not really getting a problem here. Map container's port 80 to e.g. port 8080 on host and proxy your Nginx there.

**Comment by benhartwich** [comment]
I´ve understood. Ok, that was my question - so I can set the docker nginx to another port and proxy it again.

**Comment by deniszh** [comment]
Yes, that should work. I can make graphite internal port (8080) also mappable, it should work for API requests (but not for dashboards / metric explorer)

**Comment by deniszh** [comment]
Disregard that. Please try to map port 8080 on the latest image and put Nginx there - should work properly, even with static.

**Comment by benhartwich** [comment]
Thanks, I´m running gitlab on this port. Is any other port possible?

**Comment by deniszh** [comment]
It's internal port. Just map container's 8080 to any port on host - `-p 8080:9999` in Docker. 
Or am I missing something?

**Comment by benhartwich** [comment]
I´ve tried your recommendation, but it fails: `Error response from daemon: driver failed programming external connectivity on endpoint graphite (489b1ffc024a67ab62a8418704890968a01b38486b86ed24a93661af9944e802): Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use.`

My command was: 
```
docker run -d\
>  --name graphite\
>  --restart=always\
>  -p 8080:8999\
>  -p 2003-2004:2003-2004\
>  -p 2023-2024:2023-2024\
>  -p 8125:8125/udp\
>  -p 8126:8126\
>  graphiteapp/graphite-statsd
```

**Comment by deniszh** [comment]
Sorry, mixed up host and container port, it should be vice versa. The first port is host port, second one - is container port - `-p 8999:8080`.
it's also not mandatory to map other ports too, map ports which are needed.
```
docker run -d\
>  --name graphite\
>  --restart=always\
>  -p 8999:8080\
>  -p 2003-2004:2003-2004\
>  graphiteapp/graphite-statsd
```

**Comment by deniszh** [comment]
Amended documentation to emphasize that.

**Comment by benhartwich** [comment]
Top it works.
