### ISSUE TITLE
carbon stats

### ISSUE THREAD

**Issue by noelmcgrath** [graphite-project/docker-graphite-statsd#31]
Using this to setup graphite and trying to see carbon stats but nothing showing up.
Metrics I send via statsd show up.
metric is simple:
carbon.agents.*.metricsReceived

See image. Any idea on what I need to do

![image](https://user-images.githubusercontent.com/671790/38054449-e66ae556-32ce-11e8-9373-70a795876347.png)

**Comment by deniszh** [comment]
@noelmcgrath ,
Maybe you checking data for previous runs? I just checked on fresh image - data is there.
<img width="1438" alt="screen shot 2018-04-02 at 14 06 36" src="https://user-images.githubusercontent.com/1227222/38195710-38861410-367f-11e8-844b-90156157225c.png">

**Comment by nvtkaszpir** [comment]
@noelmcgrath if you just started containers and went to the graphite web interface then you by default have drawing of last 24h on the graph - it will not show much if you just started containers because of resolution. Lower time span to 10 minutes as @deniszh  shows on his screenshot.
