### ISSUE TITLE
TIMEZONE

### ISSUE THREAD

**Issue by jmussman** [graphite-project/docker-graphite-statsd#34]
Hi, I'm looking for a way to set the timezone so graphite displays the data relative to the server's location. It looks like local_settings.py is not mapped to a place where it is persisted in your build. And, it would be really nice if the startup read the TZ environment variable and patched the local_settyings.py. Unless you have a better idea, of course :)

I could fix this in my own build, but it seems that it would be worthwhile for everybody using your build.

**Comment by deniszh** [comment]
Environment variable is a good idea, indeed. Please send PR, it will be
good addition to project.
Thanks!
