### ISSUE TITLE
'RUN pip install --upgrade pip' causes ImportError: cannot import name "main"

### ISSUE THREAD

**Issue by gavinpullen** [graphite-project/docker-graphite-statsd#36]
In our build script we clone this repo and run the docker file on Ubuntu 16.04.   
The command 'bin/sh -c **_pip install --upgrade pip_** returns a non-zero code:1  

![image](https://user-images.githubusercontent.com/1773078/39866404-7d964e9e-5448-11e8-923a-2295e76f906c.png)

Should the way pip is called be modified??  

Is there another way around this error other than the following steps??  
&nbsp;&nbsp;&nbsp;&nbsp;Manually clone repo  
&nbsp;&nbsp;&nbsp;&nbsp;Update DockerFile to hardcode older pip version  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**RUN pip install --upgrade pip==9.0.3**

**Comment by deniszh** [comment]
Ah, sorry, fix from https://github.com/graphite-project/docker-graphite-statsd/pull/35 was just merged.
