### ISSUE TITLE
Example stats script doesn't work on Mac OS X

### ISSUE THREAD

**Issue by 907th** [graphite-project/docker-graphite-statsd#37]
I found that
```
while true; do echo -n "example:$((RANDOM % 100))|c" | nc -w 1 -u 127.0.0.1 8125; done
```
script from README doesn't work on my Mac OS laptop.

The problem is that `nc` doesn't respect `-w` option and hang up forever.

I was able to generate example stats using `socat` instead:
```
while true
do
  echo -n "example:$((RANDOM % 100))|c" | socat -t 0 - UDP:192.168.99.100:8125
  sleep 1
done
```

**Comment by deniszh** [comment]
On my Mac (Sierra, 10.12.6) it works perfectly fine:
<img width="1229" alt="screen shot 2018-05-11 at 13 26 18" src="https://user-images.githubusercontent.com/1227222/39922367-167336e6-551f-11e8-8805-eae2b1c27fb5.png">
We can add alternative wat do docs, though.
