### ISSUE TITLE
Modifying graphite web's local_settings.py

### ISSUE THREAD

**Issue by gabemahoney** [graphite-project/docker-graphite-statsd#38]
Do you have any suggestions on the best way to make modifications to settings in graphite-web's local_settings.py? I thought about mapping the volume /opt/graphite/webapp/graphite/ but looking in the container there is a lot more in it than what is in github, so not sure how to get those locally first. 

Any reason this directory isn't treated the same way as /opt/graphite/conf, where I can map to an empty volume and get the config files on the host that way?

We're just trying to change the FETCH_TIMEOUT value to something a bit higher because we have a few queries which return a lot of metrics.

**Comment by deniszh** [comment]
Yep, what @nbenouss said. And REMOTE_FETCH_TIMEOUT and REMOTE_FIND_TIMEOUT variables already introduced btw.
