### ISSUE TITLE
how to open cors in this docker container?

### ISSUE THREAD

**Issue by chenzhenyang** [graphite-project/docker-graphite-statsd#41]
how to open cors in this docker container?

**Comment by deniszh** [comment]
Looks similar to https://github.com/graphite-project/docker-graphite-statsd/issues/24
I'm afraid that now it's only possible if mount own config for Nginx and put something like https://gist.github.com/oroce/8742704#file-nginx-conf-L43-L48 there.
Can be exported through env variables somehow.
