### ISSUE TITLE
Dockerhub does not list this image as official

### ISSUE THREAD

**Issue by shinberg** [graphite-project/docker-graphite-statsd#42]
Hi all,
When I was searching for official release of graphite image I followed the dockerhub, entered `graphite` and then chose 'official' in the drop down menu there on dockerhub, and no image was shown if I did that.
It took some time to find and insure that _graphiteapp/graphite-statsd_ image is official one.
I would recommend you to label that image as official so people can choose this image if they want an official image.
Thank you for having official image anyway.

**Comment by deniszh** [comment]
Docker's 'official' images are curated by Docker and have quite strict guidelines - https://docs.docker.com/docker-hub/official_repos/#how-do-i-create-a-new-official-repository
Not sure that it's worth to spend time (which looks like, a lot) on that TBH.
