### ISSUE TITLE
Support for aarch64?

### ISSUE THREAD

**Issue by markbeierl** [graphite-project/docker-graphite-statsd#43]
With a number of images (node, nginx, etc) now being runnable on multiple architectures can we add support for ARM (specifically aarch64) in this image?

**Comment by deniszh** [comment]
Not really sure if python/cffi/cairo integration will work on aarch64. But probably that's possible.

**Comment by bebehei** [comment]
> Not really sure if python/cffi/cairo integration will work on aarch64

Assume the opposite: Why shouldn't work it? :wink: 

I'm also running on `aarch64`. As the phusion image is not available for architectures other than amd64, you have to build it manually yourself.

Just a simple clone and build of both repositories in the right order will suffice:

```
git clone https://github.com/phusion/baseimage-docker
cd baseimage-docker
make
git clone https://github.com/graphite-project/docker-graphite-statsd
docker-graphite-statsd
docker build -t  graphiteapp/graphite-statsd .
```

And you should have a working graphite image.

Yeah, the problems about distribution and automated building are still unsolved, but at least you've got a working image then. Also on an Odroid C2, it takes more than 20 minutes to build all images from scratch. This also might not be feasible on every single board computer. (I don't want to know how long it'll take on a raspi). But as long dockerhub isn't supporting a way to automatically build `aarch64` images, it might be the single possible way.

**Comment by deniszh** [comment]
Thanks, @bebehei, it's good to know that at least possible. My skepticism was mostly related to cross-compiling `aarch64` docker image on amd64.

**Comment by deniszh** [comment]
Fixed in current master
