### ISSUE TITLE
GRAPHITE_STORAGE_DIR is not present inside the container

### ISSUE THREAD

**Issue by alien2003** [graphite-project/docker-graphite-statsd#44]
Tried to use this image on Kubernetes.

There was an issue with persistent storage caused by lack of `GRAPHITE_STORAGE_DIR` environment variable.

Variable `GRAPHITE_STORAGE_DIR` should be set to `/opt/graphite/storage` by default

**Comment by deniszh** [comment]
Did you try that? Passing GRAPHITE_STORAGE_DIR as env. variable should work

**Comment by alien2003** [comment]
@deniszh yes it works but I guess it should be predefined

**Comment by deniszh** [comment]
Not really getting what you mean, @alien2003 , sorry. It's present in config file and works.
Why do you think it should be predefined, could you please elaborate your use case?

**Comment by deniszh** [comment]
Yes, but why do you think it's related to GRAPHITE_STORAGE_DIR, could you please elaborate?

**Comment by deniszh** [comment]
Any news, @alien2003 ?
Thanks!
