### ISSUE TITLE
Add an Alpine Linux variant

### ISSUE THREAD

**Issue by nvllsvm** [graphite-project/docker-graphite-statsd#55]
Alpine-based images are typically much smaller than Debian-based ones.

**Comment by deniszh** [comment]
Not sure that alpine has support for all needed python modules, will check that. I have idea to decrease image size by using two stage build, but ubuntu image, though

**Comment by deniszh** [comment]
Ah, I see another problem here. Phusion baseimage using runit, and has quite specific environment, based on Ubuntu. Alpine has runit support now, but nothing else, so, porting to Alpine will require almost  complete rewrite - see https://github.com/phusion/baseimage-docker/issues/275

So, Apline support is possible, but will require some work, e.g. using https://github.com/just-containers/s6-overlay as base.

**Comment by deniszh** [comment]
PS: Please note that I switched this image to multistage now, dropping its size from 850 to 480MB - https://github.com/graphite-project/docker-graphite-statsd/pull/56
