### ISSUE TITLE
Docker run failing on the latest build

### ISSUE THREAD

**Issue by farazhaider** [graphite-project/docker-graphite-statsd#57]
Error Log

prod_statsd.1@instance-1    | E: Unable to locate package git
prod_statsd.1@instance-1    | *** /etc/my_init.d/01_conf_init.sh failed with status 100
prod_statsd.1@instance-1    | *** Killing all processes...

**Comment by deniszh** [comment]
Fixed in #58 and v1.1.4-6 released
