### ISSUE TITLE
wrong next page redirect after Django login on alternate port

### ISSUE THREAD

**Issue by heinrichmartin** [graphite-project/docker-graphite-statsd#6]
I mapped the web port of the container to 8080 on the host (`-p 8080:80`), which breaks login.

When trying to login from the homepage
1. Login link points correctly to `http://host:8080/account/login`
2. POSTing the login data wrongly `302`-redirects to `http://host/`
3. When browsing `http://host:8080/` now, I am logged in.
4. Logout redirects again to `http://host/` which is wrong.

This might bite people who want to Proxy via https, too. (Assuming host:80 --redirect--> host:443 --proxy--> container:80)

**Comment by deniszh** [comment]
Hi @heinrichmartin,
Thanks for reporting!
Probably this issue should be opened on Graphite-web, not on docker image, and not sure if it's easily fixable. 
Django just not aware of port when constructing return URL ("nextPage") in https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/account/views.py#L28-L31
But I'm not a Django expert, though. Maybe @brutasse or @cbowman0 knows?

**Comment by brutasse** [comment]
It would be interesting to have the full HTTP trace. Django normally redirects to URLs not including the host/port part. Usually something like:

`Location: /`

I would suspect an issue with nginx doing some rewriting of the location header. In development with a non-standard HTTP port, redirects are resolved properly.

**Comment by heinrichmartin** [comment]
Attached full data of the buggy request (between my FF browser and the host; `host:8080` is mapped to `container:80` in `docker run`) [login_redirect.har.txt](https://github.com/graphite-project/docker-graphite-statsd/files/1421077/login_redirect.har.txt)

Note1: the request POSTs `nextPage=/`

Note2 ([XY-Problem](http://xyproblem.info/)): I wanted to [Try Graphite in Docker and have it running in seconds](http://graphite.readthedocs.io/en/latest/install.html#docker) on an existing machine (VM) that has a catch-all-redirect from http to https (Apache). That's why I tried to `ProxyPass` only `/graphite/` of the SSL virtual host to `container:8080` - this failed even worse than the current approach.

Note3: I just detected #2 which mentions a GRAPHITE_URL, but which is not mentioned in the quick intro - did I miss anything?

**Comment by brutasse** [comment]
So yes, that's nginx sending back a full redirection. Not Django.

Regarding 3), `GRAPHITE_URL` is for Carbon, not graphite-web so I doubt setting it would help with regards to this issue.

**Comment by deniszh** [comment]
@heinrichmartin : TBH I don't know why Nginx doing that. Probably because Nginx is only redirecting traffic here, and real Graphite port internally is 8080. Did you tried different ports, not 8080?

**Comment by heinrichmartin** [comment]
It's the same for 8081.

BTW, I found these messages in the nginx error.log (but note that I cannot reproduce the second one ...):
```
2017/10/30 11:22:04 [error] 46#46: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.16.73.71, server: , request: "GET /browserheader HTTP/1.1", upstream: "http://[::1]:8080/browserheader", host: "10.0.0.1:8081", referrer: "http://10.0.0.1:8081/"
2017/10/30 11:25:24 [error] 46#46: *54 connect() failed (111: Connection refused) while connecting to upstream, client: 172.16.73.71, server: , request: "POST /account/login HTTP/1.1", upstream: "http://[::1]:8080/account/login", host: "10.0.0.1:8081", referrer: "http://10.0.0.1:8081/account/login"
```

**Comment by jameyg42** [comment]
@heinrichmartin i ran into the same where "localhost" is resolving to the IPv6 address causing Nginx to fail.  I didn't dig around for a better solution, but changing "localhost" to 127.0.0.1 in /etc/nginx/sites-enabled/graphite-statsd.conf forced IPv4.  Also, changing $host to "localhost" in the Host add_header is a hacky way to solve Django's ALLOWED_HOSTS check.

**Comment by heinrichmartin** [comment]
@jameyg42 thank you for sharing your findings. It looks like I am going to dive into the details of the image now ... How can I trace (tcpdump) the upstream connection, i.e. between nginx and graphite?

**Comment by changsijay** [comment]
looks similar to https://stackoverflow.com/questions/3391986/http-post-drops-port-in-url
if I add my the mapped docker port(`-p 8080:80`)
in `/etc/nginx/sites-enabled/graphite-statsd.conf`
```
proxy_set_header  Host      $host:8080;
```
it works, but the workaround is not flexible :(

**Comment by heinrichmartin** [comment]
> looks similar to https://stackoverflow.com/questions/3391986/http-post-drops-port-in-url

Indeed, but the "accepted answer" on SO looks like a workaround to me. The [next comment](https://stackoverflow.com/a/20752916/7231298) seems to be the correct solution:
```
proxy_set_header Host $http_host;
```

I just tried and this works for me! (This is actually an isolated change to [graphite-statsd.conf](https://github.com/graphite-project/docker-graphite-statsd/blob/master/conf/etc/nginx/sites-enabled/graphite-statsd.conf), sorry for not providing a pull request...)
