### ISSUE TITLE
RRD support still broken

### ISSUE THREAD

**Issue by aburzyn** [graphite-project/docker-graphite-statsd#63]
This is a follow up of https://github.com/graphite-project/docker-graphite-statsd/issues/61
After that one was fixed, rdd´s showed as folders but without any content.

Trying to open an rrd folder in the browser throws this in /var/log/graphite/exception.log:
```
Traceback (most recent call last):
  File "/opt/graphite/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/metrics/views.py", line 128, in find_view
    leaves_only=leaves_only,
  File "/opt/graphite/webapp/graphite/storage.py", line 264, in find
    for match in self._find(query):
  File "/opt/graphite/webapp/graphite/storage.py", line 295, in _find
    for node in result or []:
  File "/opt/graphite/webapp/graphite/finders/standard.py", line 101, in find_nodes
    for datasource_name in RRDReader.get_datasources(absolute_path):
  File "/opt/graphite/webapp/graphite/readers/rrd.py", line 61, in get_datasources
    #info = rrdtool.info(RRDReader._convert_fs_path(fs_path))
```
As far as I dug. it seems to be a bug in Graphite + Python3. 
I created this workaround in the meantime by patching the image:
```
FROM graphiteapp/graphite-statsd
# At the moment, this does not work without this patch
RUN sed \
-i \
's/return os.path.realpath(fs_path)/return os.path.realpath(fs_path).decode("utf-8")/' \
/opt/graphite/webapp/graphite/readers/rrd.py
```
That allowed me to read the rrd files.

**Comment by deniszh** [comment]
Ah, crap. That's should be properly fixed in graphite-web. I do not want to rollback to python 2.7, though. Will add your workaround to image for now, and will create proper PR for graphite-web, but it will be fixed in upcoming 1.1.5 only.

**Comment by aburzyn** [comment]
No problem for me, the purpose was to leave the issue and the workaround documented in the meantime.

**Comment by deniszh** [comment]
Fixed in https://github.com/graphite-project/graphite-web/pull/2383
