### ISSUE TITLE
Carbon-Relay Daemon Missing

### ISSUE THREAD

**Issue by Talisca** [graphite-project/docker-graphite-statsd#67]
I wonder why there is no carbon-relay daemon included?

For some tests I wanted to use docker for a simple graphite cluster and thought it would work out of the box if I modified the specific configuration files - but nope.

It would be neat if at least a docker environment variable could be set to start the carbon relay daemon.

**Comment by deniszh** [comment]
Well, that's quite simple to implement, but it's better to wait for finishing of #66 first.

**Comment by deniszh** [comment]
Fixed in 1.1.4-10, will be backported in the master branch too
