### ISSUE TITLE
Gunicorn Startup command

### ISSUE THREAD

**Issue by Randomwill28** [graphite-project/docker-graphite-statsd#68]
Is there a way to change the startup of gunicorn? Such that I can change the number of workers or add different settings. Is there a script within the container that I am not aware of? 

This is question is probably more indicative of my lack of knowledge more than anything.

**Comment by deniszh** [comment]
It's in documentation - https://github.com/graphite-project/docker-graphite-statsd#tunables
```
GRAPHITE_WSGI_PROCESSES: (4) the number of WSGI daemon processes that should be started
GRAPHITE_WSGI_THREADS: (2) the number of threads to be created to handle requests in each daemon process
GRAPHITE_WSGI_REQUEST_TIMEOUT: (65) maximum number of seconds that a request is allowed to run before the daemon process is restarted
GRAPHITE_WSGI_MAX_REQUESTS: (1000) limit on the number of requests a daemon process should process before it is shutdown and restarted.
GRAPHITE_WSGI_REQUEST_LINE: (0) The maximum size of HTTP request line in bytes.```

**Comment by deniszh** [comment]
Startupm script is https://github.com/graphite-project/docker-graphite-statsd/blob/master/conf/etc/service/graphite/run
