### ISSUE TITLE
Dashboard page shows error with graphiteapp/docker-graphite-statsd:latest image

### ISSUE THREAD

**Issue by prpalnit** [graphite-project/docker-graphite-statsd#69]
Repro steps:

* Run `docker run -d --name graphite --restart=always -p 80:80 -p 2003-2004:2003-2004 -p 2023-2024:2023-2024 -p 8125:8125/udp -p 8126:8126 graphiteapp/docker-graphite-statsd`
* Open browser and launch http://localhost

Expected: 
<img width="772" alt="screen shot 2018-11-16 at 1 49 41 pm" src="https://user-images.githubusercontent.com/13528555/48649140-88935500-e9a6-11e8-9bb4-fff3023229af.png">

Actual:
<img width="1048" alt="screen shot 2018-11-16 at 1 44 16 pm" src="https://user-images.githubusercontent.com/13528555/48648905-c6dc4480-e9a5-11e8-8677-e25cf8448bd4.png">

**Comment by deniszh** [comment]
Fixed in latest master. Ubuntu based image will be built from `ubuntu-1.1.4` branch
