### ISSUE TITLE
Statsd repeater failed to start due to generic-pool lack

### ISSUE THREAD

**Issue by andrey-avdeev** [graphite-project/docker-graphite-statsd#72]
Given:

- Offical graphite docker [repo](https://github.com/graphite-project/docker-graphite-statsd)
- Statsd-exporter in the same host + docker network
- My statsd_config:
`{
  "graphiteHost": "127.0.0.1",
  "graphitePort": 2003,
  "port": 8125,
  "flushInterval": 10000,
  "backends": [ "./backends/graphite", "./backends/repeater" ],
  "servers": [ { server: "./servers/udp", address: "0.0.0.0", port: 8125 }  ],
    "repeater": [ { host: "127.0.0.1", port: 9125 }]
}`

When:
1. Docker run graphite `docker run \
-d \
--name graphite \
--restart=always \
--network=graphite \
-p 80:80 \
-p 2003-2004:2003-2004 \
-p 2023-2024:2023-2024 \
-p 8125:8125/udp \
-p 8126:8126 \
-v /etc/graphite/conf:/opt/graphite/conf \
-v /data/graphite:/opt/graphite/storage \
-v /etc/statsd/config/config_udp.js:/opt/statsd/config_udp.js \
-v /var/log/graphite:/var/log \
graphiteapp/graphite-statsd`

Then:
1. statsd.log  - error in module.js
missing "generic-pool" in repeater.js

**Comment by deniszh** [comment]
Hi @andrey-avdeev ,
Could you please share your /etc/statsd/config/config_udp.js ?

**Comment by andrey-avdeev** [comment]
Here it is:
`{
  "graphiteHost": "127.0.0.1",
  "graphitePort": 2003,
  "port": 8125,
  "flushInterval": 10000,
  "backends": [ "./backends/graphite"
//, "./backends/repeater"
],
  "servers": [ { server: "./servers/udp", address: "0.0.0.0", port: 8125 }  ],
    "repeater": [ { host: "127.0.0.1", port: 9125 }]
}
`
Just try to configure repeater for included statsd server. 
I think, "npm install" command missing in a Dockerfile.

**Comment by deniszh** [comment]
repeater backend should be built in - and it is
```
root@4cc7871cc0c8:/# ls -al /opt/statsd/backends/
total 28
drwxr-xr-x  2 root root  4096 Dec 17 13:03 .
drwxr-xr-x 13 root root  4096 Dec 17 13:03 ..
-rw-r--r--  1 root root  1397 Nov  5 16:46 console.js
-rw-r--r--  1 root root 10843 Nov  5 16:46 graphite.js
-rw-r--r--  1 root root  3171 Nov  5 16:46 repeater.js
```
Probably you'll need full paths in config, like
```
{ "graphiteHost": "127.0.0.1", "graphitePort": 2003, "port": 8125, "flushInterval": 10000, "backends": [ "/opt/statsd/backends/graphite" //, "/opt/statsd/backends/repeater" ], "servers": [ { server: "/opt/statsd/servers/udp", address: "0.0.0.0", port: 8125 } ], "repeater": [ { host: "127.0.0.1", port: 9125 }] } 
```

**Comment by andrey-avdeev** [comment]
Sorry, i did it and found in statsd.log an error:
`17 Dec 13:08:52 - server is up INFO
module.js:478
    throw err;
    ^

Error: Cannot find module 'generic-pool'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/statsd/backends/repeater.js:6:35)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)`

**Comment by deniszh** [comment]
Sorry, I'm not a user of statsd and do not know how to configure that exactly, it's better to ask support from `statsd-sawwy` people. Default config works fine, setup is quite straightforward. And I can fix image if you find a culprit too.

**Comment by piotr1212** [comment]
> I think, "npm install" command missing in a Dockerfile.

Yup, `npm install` needs to be run from the statsd directory. Or you could symlink the dependencies to the system ones... 

Or even better, switch to https://github.com/statsite/statsite which is actively maintained, faster and does not use nodejs. I see they have a docker file, so I think you could even completely remove statsd from this dockerfile and add their docker to the compose.yml.

anyway, adding `npm install` to the dockerfile should fix this.

**Comment by deniszh** [comment]
@piotr1212 : 
>Yup, npm install needs to be run from the statsd directory. Or you could symlink the dependencies to the system ones...

just `npm install` in statsd dir? what a joke...

>Or even better, switch to https://github.com/statsite/statsite which is actively maintained, faster and does not use nodejs.

That's possible, but it's not fully compatible with statsd, so, it's a breaking change

**Comment by deniszh** [comment]
@piotr1212 : 
So, change
```
RUN git init /opt/statsd \
 && git -C /opt/statsd remote add origin "${statsd_repo}" \
 && git -C /opt/statsd fetch origin "${statsd_version}" \
 && git -C /opt/statsd checkout "${statsd_version}"
```
to
```
RUN git init /opt/statsd \
 && git -C /opt/statsd remote add origin "${statsd_repo}" \
 && git -C /opt/statsd fetch origin "${statsd_version}" \
 && git -C /opt/statsd checkout "${statsd_version}"\
 && npm install
```
should do the trick?
