### ISSUE TITLE
Document Nginx User Change

### ISSUE THREAD

**Issue by jag3773** [graphite-project/docker-graphite-statsd#75]
The release notes for https://github.com/graphite-project/docker-graphite-statsd/releases/tag/1.1.5-2 should also note that due to the switch to Alpine the user that the Nginx process runs as has changed.

For anyone upgrading from a previous version and using their previous nginx.conf file, this will cause Nginx to not run and cause problems. The code change is here https://github.com/graphite-project/docker-graphite-statsd/commit/8d74450796ff70e8bca3b2751a5cc5ec2a138c3b#diff-91e8cbe5e36ea5d88807739f99b79f71.

**Comment by deniszh** [comment]
Hello @jag3773 ,

Ah, right. Thanks for noting that!
Unfortunately, release notes are part of a release, so, it's kinda immutable. I can fix it in a master branch, but not sure if it has any use. I can also add `www-data` user to the image, but that will probably not work either.
