### ISSUE TITLE
carbon-relay is running when RELAY is not defined 

### ISSUE THREAD

**Issue by hamelg** [graphite-project/docker-graphite-statsd#80]
/etc/service/carbon-relay/run runs unconditionally carbon-relay service.
There is a typo in file. The test has no effect
[[ -n ${RELAY} ]] || exit 1
it should be 
[[ -n "${RELAY}" ]] || exit 1

**Comment by deniszh** [comment]
Thanks! Fixed in master

**Comment by deniszh** [comment]
Fix released in v1.1.5-4
