### ISSUE TITLE
Logrotate not working with 1.1.5-4

### ISSUE THREAD

**Issue by Stephan3555** [graphite-project/docker-graphite-statsd#82]
Good afternoon,

Logrotate seems still not to work even after the changes in 1.1.5-4.

Wrote a detailed report under the old post:
https://github.com/graphite-project/docker-graphite-statsd/issues/81#issuecomment-456022627

See issue https://github.com/graphite-project/docker-graphite-statsd/issues/81

Greetings,
Stephan

**Comment by deniszh** [comment]
Right, Alpine has no cron installed / running by default. Fixed in 1.1.5-6, please test @Stephan3555
