### ISSUE TITLE
How to establish graphite-statsd is ready?

### ISSUE THREAD

**Issue by electrofelix** [graphite-project/docker-graphite-statsd#83]
Found that running this image, that it can take up to 2 minutes before dummy stats sent into the running container before querying for the metric returned usable results.

Run the image with:
```
docker run --rm -d \
    --name graphite-statsd \
    -p 8080:80 \
    -p 2003-2004:2003-2004 \
    -p 2023-2024:2023-2024 \
    -p 8125:8125/udp \
    -p 127.0.0.1:8126:8126 \
    graphiteapp/graphite-statsd:latest
```

This unfortunately makes it very difficult to determine when the services in the container are ready for use.

Some enquiries in #graphite on Freenode IRC suggested that it takes some time for a whisper file to be created as once about 90 seconds has past after the initial stat was submitted, any subsequent entries to the same stats are picked up almost immediately.

Is this the source of the delay? Is there anything here someone using the image could do?

If there is nothing to be done, seems like the delay from the initial stat being emitted and showing up in graphite should be mentioned in the documentation around verifying it is working to avoid any confusion.

**Comment by deniszh** [comment]
Hello @electrofelix,

TBH I’m not really understand what’s issue here. There’re can be ton of issues causing metric propagation delay (e.g. file creation speed is limited to prevent disk overload or something else) but you can safely assume that graphite is ready for metric ingestion when it starts to listen port 2003 and ready for rendering when web return non 500 code.

**Comment by electrofelix** [comment]
@deniszh thanks for taking some time. I guess the main problem is I don't know where to look to understand why it's taking so long, and I was caught by surprise that once the initial delay was over records appeared available via the API very quickly, so it's not a constant propagation delay.

Normally I'd expect that once it's possible to send some records in and get a valid response on the web, that the stats would be available to query directly from the web API.

So after getting it working, to confirm that any configuration options changes made locally didn't cause any issue, I set up a simple test to do the following:

* start the container with provide configuration
* wait for API to return 200
* emit a single record
* query for it from the web API

Only to discover that even though the test was waiting for the API to be ready, basically had to poll for up to 120 seconds if the container had just been started. Even if the container was started two minutes ago, it seems that something happens on the first time the record for a new stat is sent in, before it propagates, but once that is done subsequent stat updates are very quick.
