### ISSUE TITLE
Does not work with empty /opt/graphite/conf

### ISSUE THREAD

**Issue by jrhunger** [graphite-project/docker-graphite-statsd#84]
As per the README.md, "The container will initialize properly if you mount empty volumes at /opt/graphite/conf, /opt/graphite/storage, or /opt/statsd/config."

However, with empty /opt/graphite/conf directory, carbon continually prints this message to the logs:
Error: missing required config '/opt/graphite/conf/carbon.conf'

Graphite web starts, but has no data.  No files are created in /opt/graphite/conf volume/directory

Current version of hopsoft/graphite-statsd *does* work with empty /opt/graphite/conf directory, and populates it with the following files:
aggregation-rules.conf
blacklist.conf
carbon.amqp.conf
carbon.conf
dashboard.conf
graphTemplates.conf
relay-rules.conf
rewrite-rules.conf
storage-aggregation.conf
storage-schemas.conf
whitelist.conf

**Comment by deniszh** [comment]
Yes, another artifact of migrating to  Alpine. Fixed in 1.1.5-5
