### ISSUE TITLE
nginx : Connection refused ... upstream: "http://[::1]:8080

### ISSUE THREAD

**Issue by hamelg** [graphite-project/docker-graphite-statsd#87]
I upgraded from 1.1.3 to 1.1.5-6.
Now, log/nginx/error.log is full of these errors : 

`2019/02/08 15:00:39 [error] 45#45: *62 connect() failed (111: Connection refused) while connecting to upstream, client: 10.154.yy.xx, server: , request: "POST /render HTTP/1.1", upstream: "http://[::1]:8080/render", host: "xxx.yy.zz"`

Nginx tries to connect with ipv6 protocol to graphite-web but it can't : graphite-web is listening in ipv4 only. 

replace the string "localhost" with "127.0.0.1" in /etc/nginx/sites-enabled/graphite-statsd.conf and theses errors vanish.

**Comment by deniszh** [comment]
Ok, thanks for report. Will fix.

**Comment by deniszh** [comment]
Fixed in v1.1.5-7
