### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by hamelg** [graphite-project/docker-graphite-statsd#89]
Hello,
We encounter performance issue when using the graphiteapp/graphite-statsd image. We have posted an issue here : 
https://github.com/graphite-project/carbon/issues/839

**Comment by deniszh** [comment]
Your results looking very strange, you can use e.g. https://github.com/graphite-project/graphite-test-docker project for testing Graphite in Docker.

**Comment by hamelg** [comment]
The issue is described here https://github.com/graphite-project/carbon/issues/840
