### ISSUE TITLE
storing events in external database

### ISSUE THREAD

**Issue by moix** [graphite-project/docker-graphite-statsd#95]
Hi, I'd like to use different database for storing the events instead the default sqlite but cannot find in the docker run parameters if there's an easy way to modify it.
Any idea how to change to mysql for example?

Thanks in advance!

**Comment by deniszh** [comment]
Unfortunately, there's no easy way to fix that using the environment variable. You need to edit or mount `local_settings.py` config with a different database connection and migrate data from SQLite. You can check for example this gist - https://gist.github.com/toni-moreno/9779979

**Comment by moix** [comment]
alright thanks, giving a try now to these steps. What about image dependencies? should I update it with any missing package for mysql?

**Comment by deniszh** [comment]
Riiight... Libraries and python packages also needed.
Maybe it should be included in base image too.
E.g. for 
Mysql - https://hub.docker.com/r/mio101/py3-mysqlclient-alpine/ 
Postgres - https://github.com/psycopg/psycopg2/issues/684

**Comment by deniszh** [comment]
@moix: Should be fixed in v1.1.5-11, please test.
