### ISSUE TITLE
Why can not change storage-schemas.conf?

### ISSUE THREAD

**Issue by sevaTechoPark** [graphite-project/docker-graphite-statsd#99]
I use dockerfile, and when I COPY this file from host everything is good, but if I try to change this file (in dockerfile with https://www.gnu.org/software/sed/manual/sed.html) this file does not change

I spent 4 hours and I have no idea why is this happening
I am very interested to know, apparently I have spaces in Linux
But I am sure that I change this file right
does not work ONLY in this folder /opt/graphite/conf/

**Comment by deniszh** [comment]
Hi @sevaTechoPark ,
Could you please elaborate your question a bit? E.g. provide exact change which you try to achieve, what steps did you for that, etc.

**Comment by deniszh** [comment]
Also, change probably not even needed. `opt/graphite/conf` is a volume, so, you can mount it separately, with own config.

**Comment by sevaTechoPark** [comment]
`Dockerfile`:
```
FROM graphiteapp/graphite-statsd

ARG RETENTIONS_COLLECTD
ARG RETENTIONS_NGINX

ENV PATH_TO_CARBON_CONFIG_DIR /opt/graphite/conf/

COPY storage-schemas.conf $PATH_TO_CARBON_CONFIG_DIR

RUN cat "${PATH_TO_CARBON_CONFIG_DIR}storage-schemas.conf"
RUN sed -i -e \
	"s!\${RETENTIONS_COLLECTD}!$RETENTIONS_COLLECTD!g;\
     s!\${RETENTIONS_NGINX}!$RETENTIONS_NGINX!g"\
  "${PATH_TO_CARBON_CONFIG_DIR}storage-schemas.conf"
RUN cat "${PATH_TO_CARBON_CONFIG_DIR}storage-schemas.conf"
```
`storage-schemas.conf`:
```
[collectd]
pattern = ^collectd
retentions = ${RETENTIONS_COLLECTD}

[mtail_nginx]
pattern = ^nginx
retentions = ${RETENTIONS_NGINX}
```

`docker image build --no-cache --build-arg RETENTIONS_COLLECTD=1s:1m --build-arg RETENTIONS_NGINX=2s:2m .`

try it.
then run `sed` without `-i` and you will be surprised
